// Code generated by go-swagger; DO NOT EDIT.

package container

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// WaitExitError container waiting error, if any
//
// swagger:model WaitExitError
type WaitExitError struct {

	// Details of an error
	Message string `json:"Message,omitempty"`
}

// Validate validates this wait exit error
func (m *WaitExitError) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this wait exit error based on context it is used
func (m *WaitExitError) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *WaitExitError) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *WaitExitError) UnmarshalBinary(b []byte) error {
	var res WaitExitError
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
