// Code generated by mobyextgen. DO NOT EDIT.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: internal/extensions/example/greeter/v0/greeter.proto

package protogen

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HelloReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HelloReply) Reset() {
	*x = HelloReply{}
	mi := &file_internal_extensions_example_greeter_v0_greeter_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HelloReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloReply) ProtoMessage() {}

func (x *HelloReply) ProtoReflect() protoreflect.Message {
	mi := &file_internal_extensions_example_greeter_v0_greeter_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloReply.ProtoReflect.Descriptor instead.
func (*HelloReply) Descriptor() ([]byte, []int) {
	return file_internal_extensions_example_greeter_v0_greeter_proto_rawDescGZIP(), []int{0}
}

func (x *HelloReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type HelloRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HelloRequest) Reset() {
	*x = HelloRequest{}
	mi := &file_internal_extensions_example_greeter_v0_greeter_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HelloRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloRequest) ProtoMessage() {}

func (x *HelloRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_extensions_example_greeter_v0_greeter_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloRequest.ProtoReflect.Descriptor instead.
func (*HelloRequest) Descriptor() ([]byte, []int) {
	return file_internal_extensions_example_greeter_v0_greeter_proto_rawDescGZIP(), []int{1}
}

func (x *HelloRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_internal_extensions_example_greeter_v0_greeter_proto protoreflect.FileDescriptor

const file_internal_extensions_example_greeter_v0_greeter_proto_rawDesc = "" +
	"\n" +
	"4internal/extensions/example/greeter/v0/greeter.proto\x12,org.mobyproject.extension.example.greeter.v0\"&\n" +
	"\n" +
	"HelloReply\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"\"\n" +
	"\fHelloRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name2\x88\x01\n" +
	"\aGreeter\x12}\n" +
	"\x05Greet\x12:.org.mobyproject.extension.example.greeter.v0.HelloRequest\x1a8.org.mobyproject.extension.example.greeter.v0.HelloReplyBIZGgithub.com/moby/moby/v2/internal/extensions/example/greeter/v0/protogenb\x06proto3"

var (
	file_internal_extensions_example_greeter_v0_greeter_proto_rawDescOnce sync.Once
	file_internal_extensions_example_greeter_v0_greeter_proto_rawDescData []byte
)

func file_internal_extensions_example_greeter_v0_greeter_proto_rawDescGZIP() []byte {
	file_internal_extensions_example_greeter_v0_greeter_proto_rawDescOnce.Do(func() {
		file_internal_extensions_example_greeter_v0_greeter_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_extensions_example_greeter_v0_greeter_proto_rawDesc), len(file_internal_extensions_example_greeter_v0_greeter_proto_rawDesc)))
	})
	return file_internal_extensions_example_greeter_v0_greeter_proto_rawDescData
}

var file_internal_extensions_example_greeter_v0_greeter_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_internal_extensions_example_greeter_v0_greeter_proto_goTypes = []any{
	(*HelloReply)(nil),   // 0: org.mobyproject.extension.example.greeter.v0.HelloReply
	(*HelloRequest)(nil), // 1: org.mobyproject.extension.example.greeter.v0.HelloRequest
}
var file_internal_extensions_example_greeter_v0_greeter_proto_depIdxs = []int32{
	1, // 0: org.mobyproject.extension.example.greeter.v0.Greeter.Greet:input_type -> org.mobyproject.extension.example.greeter.v0.HelloRequest
	0, // 1: org.mobyproject.extension.example.greeter.v0.Greeter.Greet:output_type -> org.mobyproject.extension.example.greeter.v0.HelloReply
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_internal_extensions_example_greeter_v0_greeter_proto_init() }
func file_internal_extensions_example_greeter_v0_greeter_proto_init() {
	if File_internal_extensions_example_greeter_v0_greeter_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_extensions_example_greeter_v0_greeter_proto_rawDesc), len(file_internal_extensions_example_greeter_v0_greeter_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_extensions_example_greeter_v0_greeter_proto_goTypes,
		DependencyIndexes: file_internal_extensions_example_greeter_v0_greeter_proto_depIdxs,
		MessageInfos:      file_internal_extensions_example_greeter_v0_greeter_proto_msgTypes,
	}.Build()
	File_internal_extensions_example_greeter_v0_greeter_proto = out.File
	file_internal_extensions_example_greeter_v0_greeter_proto_goTypes = nil
	file_internal_extensions_example_greeter_v0_greeter_proto_depIdxs = nil
}
