// Code generated by mobyextgen. DO NOT EDIT.
package protogen

import (
	context "context"
	extensions "github.com/moby/moby/v2/internal/extensions"
	clientpoint "github.com/moby/moby/v2/internal/extensions/clientpoint"
	greeterv0 "github.com/moby/moby/v2/internal/extensions/example/greeter/v0"
	serverpoint "github.com/moby/moby/v2/internal/extensions/serverpoint"
	grpc "google.golang.org/grpc"
)

// ServerPoint serves the Greeter point: it registers the point's gRPC service for
// a provider with an SDK server. A binary passes it to (*sdk.Server).Register.
var ServerPoint = serverpoint.Registration{
	Point: greeterv0.Point.ID(),
	Register: func(r grpc.ServiceRegistrar, impl any) {
		RegisterGreeterServer(r, &grpcServer{impl: impl.(greeterv0.Greeter)})
	},
}

// ClientProvider builds a broker provider for the Greeter point from an
// out-of-process gRPC connection.
func ClientProvider(conn grpc.ClientConnInterface) extensions.Provider {
	return greeterv0.Point.Provide(&grpcClient{client: NewGreeterClient(conn)})
}

// ClientPoint registers ClientProvider for the Greeter point with a host.
var ClientPoint = clientpoint.Registration{Point: greeterv0.Point.ID(), Provider: ClientProvider}

type grpcServer struct {
	UnimplementedGreeterServer
	impl greeterv0.Greeter
}

func (s *grpcServer) Greet(ctx context.Context, req *HelloRequest) (*HelloReply, error) {
	resp, err := s.impl.Greet(ctx, helloRequestFromProto(req))
	if err != nil {
		return nil, err
	}
	return helloReplyToProto(resp), nil
}

type grpcClient struct {
	client GreeterClient
}

func (c *grpcClient) Greet(ctx context.Context, req *greeterv0.HelloRequest) (*greeterv0.HelloReply, error) {
	resp, err := c.client.Greet(ctx, helloRequestToProto(req))
	if err != nil {
		return nil, err
	}
	return helloReplyFromProto(resp), nil
}

func helloReplyToProto(in *greeterv0.HelloReply) *HelloReply {
	if in == nil {
		return nil
	}
	out := &HelloReply{}
	out.Message = in.Message
	return out
}

func helloReplyFromProto(in *HelloReply) *greeterv0.HelloReply {
	if in == nil {
		return nil
	}
	out := &greeterv0.HelloReply{}
	out.Message = in.GetMessage()
	return out
}

func helloRequestToProto(in *greeterv0.HelloRequest) *HelloRequest {
	if in == nil {
		return nil
	}
	out := &HelloRequest{}
	out.Name = in.Name
	return out
}

func helloRequestFromProto(in *HelloRequest) *greeterv0.HelloRequest {
	if in == nil {
		return nil
	}
	out := &greeterv0.HelloRequest{}
	out.Name = in.GetName()
	return out
}
