#!/bin/bash
set -e

DEST=$1
BINARY_NAME="docker-$VERSION"
SYMLINK_NAME=docker
if [ "$(go env GOOS)" = 'windows' ]; then
    BINARY_NAME+='.exe'
    SYMLINK_NAME+='.exe'
fi

go build \
	-o "$DEST/$BINARY_NAME" \
	"${BUILDFLAGS[@]}" \
	-ldflags "
		$LDFLAGS
		$LDFLAGS_STATIC_DOCKER
	" \
	./docker
echo "Created binary: $DEST/$BINARY_NAME"
ln -sf "$BINARY_NAME" "$DEST/$SYMLINK_NAME"

hash_files "$DEST/$BINARY_NAME"
