// Code generated by swagger-gen. DO NOT EDIT

package registry

type AuthenticateOKBody struct {
	// An opaque token used to authenticate a user after a successful login
	IdentityToken string `json:"IdentityToken,omitempty"`
	// The status of the authentication
	Status string `json:"Status"`
}
