module/client:
  - changed-files:
    - any-glob-to-any-file: 'client/**'

module/api:
  - changed-files:
    - any-glob-to-any-file: 'api/**'

area/daemon:
  - changed-files:
    - any-glob-to-any-file: 'daemon/**'

area/builder/buildkit:
  - changed-files:
    - any-glob-to-any-file:
      - 'daemon/internal/builder-next/**'
      - 'vendor/github.com/moby/buildkit/**'

area/builder/classic-builder:
  - changed-files:
    - any-glob-to-any-file:
      - 'daemon/images/*_build*'
      - 'daemon/builder/**'

area/builder:
  - changed-files:
    - any-glob-to-any-file:
      - 'daemon/internal/builder-next/**'
      - 'daemon/images/*_build*'
      - 'daemon/builder/**'
      - 'vendor/github.com/moby/buildkit/**'

area/networking:
  - changed-files:
    - any-glob-to-any-file:
      - 'api/types/network/**'
      - 'daemon/network*'
      - 'daemon/network/**'
      - 'integration/network/**'
      - 'integration/networking/**'

area/volumes:
  - changed-files:
    - any-glob-to-any-file:
      - 'api/types/volume/**'
      - 'daemon/volume/**'
      - 'integration/volume/**'

area/swarm:
  - changed-files:
    - any-glob-to-any-file:
      - 'api/types/swarm/**'
      - 'daemon/cluster/**'

area/images:
  - changed-files:
    - any-glob-to-any-file:
      - 'api/types/image/**'
      - 'daemon/images/**'
      - 'integration/image/**'

area/logging:
  - all:
    - changed-files:
      - any-glob-to-any-file:
        - 'daemon/logger/**'
        - '**/*log*'
      - all-globs-to-all-files: '!vendor/**'

area/security:
  - all:
    - changed-files:
      - any-glob-to-any-file:
        - '**/*apparmor*'
        - '**/*seccomp*'
        - '**/*selinux*'
      - all-globs-to-all-files: '!vendor/**'

area/security/apparmor:
  - all:
    - changed-files:
      - any-glob-to-any-file:
        - '**/*apparmor*'
        - 'contrib/apparmor/**'
      - all-globs-to-all-files: '!vendor/**'

area/security/selinux:
  - all:
    - changed-files:
      - any-glob-to-any-file:
        - '**/*selinux*'
        - 'contrib/selinux/**'
      - all-globs-to-all-files: '!vendor/**'

area/security/seccomp:
  - all:
    - changed-files:
      - any-glob-to-any-file: '**/*seccomp*'
      - all-globs-to-all-files: '!vendor/**'

area/systemd:
  - all:
    - changed-files:
      - any-glob-to-any-file:
        - '**/*systemd*'
        - 'contrib/init/systemd/**'
      - all-globs-to-all-files: '!vendor/**'

area/contrib:
  - changed-files:
    - any-glob-to-any-file: 'contrib/**'

area/packaging:
  - changed-files:
    - any-glob-to-any-file:
      # files used in packaging
      - 'contrib/dockerd-rootless.sh'
      - 'contrib/dockerd-rootless-setuptool.sh'
      - 'contrib/init/systemd/**'

containerd-integration:
  - changed-files:
    - any-glob-to-any-file: 'daemon/containerd/**'

area/rootless:
  - all:
    - changed-files:
      - any-glob-to-any-file:
        - '**/*rootless*'
        - 'contrib/dockerd-rootless*'
      - all-globs-to-all-files: '!vendor/**'

area/testing:
  - all:
    - changed-files:
      - any-glob-to-any-file:
        - 'integration/**'
        - 'integration-cli/**'
        - '**/*_test.go'
        - 'internal/test*'
        - 'internal/testutil/**'
      - all-globs-to-all-files: '!vendor/**'

area/docs:
  - all:
    - changed-files:
      - any-glob-to-any-file:
        - 'api/docs/*.yaml'
        - 'docs/**'
        - '**/*.md'
        - 'man/**'
      - all-globs-to-all-files: '!vendor/**'

area/dependencies:
  - all:
    - changed-files:
      - any-glob-to-any-file:
        - 'go.mod'
        - 'go.sum'
        - 'vendor/**'
      - all-globs-to-all-files:
        - '!client/**'
        - '!api/**'

area/ci:
  - changed-files:
    - any-glob-to-any-file: '.github/**'

platform/windows:
  - all:
    - changed-files:
      - any-glob-to-any-file:
        - '**/*_windows.go'
        - 'Dockerfile.windows'
      - all-globs-to-all-files: '!vendor/**'

impact/changelog:
  - changed-files:
    - any-glob-to-any-file: 'api/docs/CHANGELOG.md'
