version: "2"

run:
  concurrency: 2
  go: "1.26"

linters:
  enable:
    - depguard
    - gosec
    - importas
    - misspell
    - revive
    - unconvert

  disable:
    - errcheck

  settings:
    importas:
      # Do not allow unaliased imports of aliased packages.
      no-unaliased: true

      alias:
        # Enforce alias to prevent it accidentally being used instead of our
        # own errdefs package (or vice-versa).
        - pkg: github.com/containerd/containerd/errdefs
          alias: cerrdefs
        - pkg: github.com/opencontainers/image-spec/specs-go/v1
          alias: ocispec

    govet:
      disable:
        - shadow

    gosec:
      excludes:
        # TODO: evaluate these and fix where needed: G307: Deferring unsafe method "*os.File" on type "Close" (gosec)
        - G103 # Audit the use of unsafe block
        - G104 # Audit errors not checked
        - G115 # FIXME temporarily suppress 'G115: integer overflow conversion': it produces many hits, some of which may be false positives, and need to be looked at; see https://github.com/moby/moby/issues/48358
        - G117 # Potential exposure of secrets via JSON/YAML/XML/TOML marshaling
        - G120 # Unbounded form parsing in HTTP handlers can cause memory exhaustion
        - G122 # Filesystem TOCTOU race risk in filepath.Walk/WalkDir callbacks
        - G204 # Audit use of command execution
        - G301 # Poor file permissions used when creating a directory
        - G302 # Poor file permissions used when creating a file or using chmod
        - G304 # File path provided as taint input
        - G306 # Poor file permissions used when writing to a file
        - G307 # Poor file permissions used when creating a file with os.Create
        - G602 # Possible slice bounds out of range (has false positives)
        - G703 # Path traversal via taint analysis
        - G704 # SSRF via taint analysis
        - G705 # XSS via taint analysis

    depguard:
      rules:
        main:
          deny:
            - pkg: io/ioutil
              desc: The io/ioutil package has been deprecated, see https://go.dev/doc/go1.16#ioutil
            - pkg: "github.com/stretchr/testify/assert"
              desc: Use "gotest.tools/v3/assert" instead
            - pkg: "github.com/stretchr/testify/require"
              desc: Use "gotest.tools/v3/assert" instead
            - pkg: "github.com/stretchr/testify/suite"
              desc: Do not use
            - pkg: "github.com/containerd/containerd/errdefs"
              desc: The errdefs package has moved to a separate module, https://github.com/containerd/errdefs
            - pkg: "github.com/containerd/containerd/log"
              desc: The logs package has moved to a separate module, https://github.com/containerd/log
            - pkg: "github.com/containerd/containerd/pkg/userns"
              desc: Use github.com/moby/sys/userns instead.
            - pkg: "github.com/opencontainers/runc/libcontainer/userns"
              desc: Use github.com/moby/sys/userns instead.
    revive:
      rules:
        # FIXME make sure all packages have a description. Currently, there's many packages without.
        - name: package-comments
          disabled: true
        - name: redefines-builtin-id

    staticcheck:
      checks:
        - "all"
        - "-ST1000" # Incorrect or missing package comment
        - "-ST1003" # Poorly chosen identifier
        - "-ST1005" # Incorrectly formatted error string
        - "-ST1016" # Use consistent method receiver names
        - "-ST1020" # The documentation of an exported function should start with the function's name
        - "-ST1021" # The documentation of an exported type should start with type's name
        - "-ST1022" # The documentation of an exported variable or constant should start with variable's name
        - "-QF1001" # Apply De Morgan's law
        - "-QF1002" # Convert untagged switch to tagged switch
        - "-QF1003" # Convert if/else-if chain to tagged switch
        - "-QF1008" # Omit embedded fields from selector expression

  exclusions:
    generated: lax

    # We prefer to use an "exclude-list" so that new "default" exclusions are not
    # automatically inherited. We can decide whether or not to follow upstream
    # defaults when updating golang-ci-lint versions.
    # Unfortunately, this means we have to copy the whole exclusion pattern, as
    # (unlike the "include" option), the "exclude" option does not take exclusion
    # ID's.
    #
    # These exclusion patterns are copied from the default excluses at:
    # https://github.com/golangci/golangci-lint/blob/v1.46.2/pkg/config/issues.go#L10-L104

    rules:
      # EXC0001
      - text: "Error return value of .((os\\.)?std(out|err)\\..*|.*Close|.*Flush|os\\.Remove(All)?|.*print(f|ln)?|os\\.(Un)?Setenv). is not checked"
        linters:
          - errcheck

      # Exclude some linters from running on tests files.
      - path: _test\.go
        linters:
          - errcheck
          - gosec

      # Suppress golint complaining about generated types in api/types/
      - text: "type name will be used as (container|volume)\\.(Container|Volume).* by other packages, and that stutters; consider calling this"
        path: "api/types/(volume|container)/"
        linters:
          - revive
      # FIXME temporarily suppress these (see https://github.com/gotestyourself/gotest.tools/issues/272)
      - text: "SA1019: (assert|cmp|is)\\.ErrorType is deprecated"
        linters:
          - staticcheck
    paths:
      - docs
      - third_party$
      - builtin$
      - examples$

issues:
  # Maximum issues count per one linter. Set to 0 to disable. Default is 50.
  max-issues-per-linter: 0

  # Maximum count of issues with the same text. Set to 0 to disable. Default is 3.
  max-same-issues: 0

formatters:
  enable:
    - goimports
  exclusions:
    generated: lax
    paths:
      - docs
      - third_party$
      - builtin$
      - examples$
