linters:
  enable:
    - deadcode
    - goimports
    - gosec
    - gosimple
    - govet
    - ineffassign
    - misspell
    - revive
    - staticcheck
    - structcheck
    - typecheck
    - unconvert
    - unused
    - varcheck

  disable:
    - errcheck

  run:
    build-tags:
      - journald
      - seccomp
    concurrency: 2
    modules-download-mode: vendor

    skip-dirs:
      - bundles
      - docs
      # TODO: This package should be completely removed
      - libnetwork/client/mflag

linters-settings:
  govet:
    check-shadowing: false
  gosec:
    # Available rules: https://github.com/securego/gosec#available-rules
    excludes:
      - G103 # Audit the use of unsafe block
      - G104 # Audit errors not checked
      - G201 # SQL query construction using format string
      - G202 # SQL query construction using string concatenation
      - G204 # Audit use of command execution
      - G301 # Poor file permissions used when creating a directory
      - G302 # Poor file permissions used with chmod
      - G304 # Potential file inclusion via variable
      - G306 # Poor file permissions used when writing to a new file
      - G307 # Deferring a method which returns an error

issues:
  # The default exclusion rules are a bit too permissive, so copying the relevant ones below
  exclude-use-default: false

  # Cherry-pick some of the default exclusion rules to disable
  exclude:
    - EXC0001 # Error return value of .((os\\.)?std(out|err)\\..*|.*Close|.*Flush|os\\.Remove(All)?|.*printf?|os\\.(Un)?Setenv). is not checked
    - EXC0003 # func name will be used as test\.Test.* by other packages, and that stutters; consider calling this

  exclude-rules:
    # Exclude some linters from running on tests files.
    - path: _test\.go
      linters:
        - errcheck
        - gosec

    # Suppress golint complaining about generated types in api/types/
    - text: "type name will be used as (container|volume)\\.(Container|Volume).* by other packages, and that stutters; consider calling this"
      path: "api/types/(volume|container)/"
      linters:
        - golint
    # FIXME temporarily suppress these. See #39924
    - text: "SA1019: .*\\.Xattrs is deprecated: Use PAXRecords instead"
      linters:
        - staticcheck
    # FIXME temporarily suppress these. See #39926
    - text: "SA1019: httputil.NewClientConn"
      linters:
        - staticcheck
    # FIXME temporarily suppress these (related to the ones above)
    - text: "SA1019: httputil.ErrPersistEOF"
      linters:
        - staticcheck
    # FIXME temporarily suppress these for false positives in tests (see https://github.com/dominikh/go-tools/issues/1022)
    - text: "SA5011"
      path: _test\.go
      linters:
        - staticcheck
    # This code is doing some fun stuff with reflect and it trips up the linter.
    - text: "field `foo` is unused"
      path: "libnetwork/options/options_test.go"
      linters:
        - structcheck
        - unused
    # This field is only used on windows but is defined in a platform agnostic file.
    # The linter doesn't understand that the field is used.
    - text: "`resolverOnce` is unused"
      path: libnetwork/network.go
      linters:
        - structcheck
        - unused

  # Maximum issues count per one linter. Set to 0 to disable. Default is 50.
  max-issues-per-linter: 0

  # Maximum count of issues with the same text. Set to 0 to disable. Default is 3.
  max-same-issues: 0
