package types

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

// ErrorResponse Represents an error.
// swagger:model ErrorResponse
type ErrorResponse struct {

	// Additional details about the error (for debugging purposes).
	//
	// This field is only propagated if the daemon is started with
	// the `DOCKER_DEBUG_TRACE` variable set, and omitted otherwise.
	//
	Details *string `json:"details,omitempty"`

	// The error message.
	// Required: true
	Message string `json:"message"`
}
