package types

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

// ImageUsage image usage
// swagger:model ImageUsage
type ImageUsage struct {

	// containers
	// Required: true
	Containers int64 `json:"Containers"`

	// Id
	// Required: true
	ID string `json:"Id"`

	// shared size
	// Required: true
	SharedSize int64 `json:"SharedSize"`

	// size
	// Required: true
	Size int64 `json:"Size"`

	// virtual size
	// Required: true
	VirtualSize int64 `json:"VirtualSize"`
}
