// Code generated by swagger-gen. DO NOT EDIT

package types

// Information about a container's graph driver.
type GraphDriverData struct {
	Data map[string]string `json:"Data"`
	Name string            `json:"Name"`
}
type ImageDeleteResponseItem struct {
	// The image ID of an image that was deleted
	Deleted string `json:"Deleted,omitempty"`
	// The image ID of an image that was untagged
	Untagged string `json:"Untagged,omitempty"`
}
type ImageSummary struct {
	Containers  int64             `json:"Containers"`
	Created     int64             `json:"Created"`
	ID          string            `json:"Id"`
	Labels      map[string]string `json:"Labels"`
	ParentID    string            `json:"ParentId"`
	RepoDigests []string          `json:"RepoDigests"`
	RepoTags    []string          `json:"RepoTags"`
	SharedSize  int64             `json:"SharedSize"`
	Size        int64             `json:"Size"`
	VirtualSize int64             `json:"VirtualSize"`
}
