package types

import "github.com/docker/docker/api/types/plugins"

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

// PluginEnv plugin env
// swagger:model PluginEnv
type PluginEnv = plugins.PluginEnv
