package types

import "github.com/docker/docker/api/types/swarm"

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

// ServiceUpdateResponse service update response
// swagger:model ServiceUpdateResponse
type ServiceUpdateResponse = swarm.ServiceUpdateResponse
