// Code generated by mobyextgen. DO NOT EDIT.
package protogen

import (
	context "context"
	createspecv0 "github.com/moby/moby/v2/extpoints/createspec/v0"
	extensions "github.com/moby/moby/v2/internal/extensions"
	clientpoint "github.com/moby/moby/v2/internal/extensions/clientpoint"
	serverpoint "github.com/moby/moby/v2/internal/extensions/serverpoint"
	grpc "google.golang.org/grpc"
)

// ServerPoint serves the CreateSpecHook point: it registers the point's gRPC service for
// a provider with an SDK server. A binary passes it to (*sdk.Server).Register.
var ServerPoint = serverpoint.Registration{
	Point: createspecv0.Point.ID(),
	Register: func(r grpc.ServiceRegistrar, impl any) {
		RegisterCreateSpecHookServer(r, &grpcServer{impl: impl.(createspecv0.Hook)})
	},
}

// ClientProvider builds a broker provider for the CreateSpecHook point from an
// out-of-process gRPC connection.
func ClientProvider(conn grpc.ClientConnInterface) extensions.Provider {
	return createspecv0.Point.Provide(&grpcClient{client: NewCreateSpecHookClient(conn)})
}

// ClientPoint registers ClientProvider for the CreateSpecHook point with a host.
var ClientPoint = clientpoint.Registration{Point: createspecv0.Point.ID(), Provider: ClientProvider}

type grpcServer struct {
	UnimplementedCreateSpecHookServer
	impl createspecv0.Hook
}

func (s *grpcServer) CreateSpec(ctx context.Context, req *SpecRequest) (*SpecAdjustment, error) {
	resp, err := s.impl.CreateSpec(ctx, specRequestFromProto(req))
	if err != nil {
		return nil, err
	}
	return specAdjustmentToProto(resp), nil
}

func (s *grpcServer) Validate(ctx context.Context, req *SpecRequest) (*ValidateResponse, error) {
	if err := s.impl.Validate(ctx, specRequestFromProto(req)); err != nil {
		return nil, err
	}
	return &ValidateResponse{}, nil
}

type grpcClient struct {
	client CreateSpecHookClient
}

func (c *grpcClient) CreateSpec(ctx context.Context, req *createspecv0.SpecRequest) (*createspecv0.SpecAdjustment, error) {
	resp, err := c.client.CreateSpec(ctx, specRequestToProto(req))
	if err != nil {
		return nil, err
	}
	return specAdjustmentFromProto(resp), nil
}

func (c *grpcClient) Validate(ctx context.Context, req *createspecv0.SpecRequest) error {
	_, err := c.client.Validate(ctx, specRequestToProto(req))
	return err
}

func specAdjustmentToProto(in *createspecv0.SpecAdjustment) *SpecAdjustment {
	if in == nil {
		return nil
	}
	out := &SpecAdjustment{}
	out.Spec = in.Spec
	return out
}

func specAdjustmentFromProto(in *SpecAdjustment) *createspecv0.SpecAdjustment {
	if in == nil {
		return nil
	}
	out := &createspecv0.SpecAdjustment{}
	out.Spec = in.GetSpec()
	return out
}

func specRequestToProto(in *createspecv0.SpecRequest) *SpecRequest {
	if in == nil {
		return nil
	}
	out := &SpecRequest{}
	out.ContainerId = in.ContainerID
	out.Name = in.Name
	out.Spec = in.Spec
	out.Labels = in.Labels
	return out
}

func specRequestFromProto(in *SpecRequest) *createspecv0.SpecRequest {
	if in == nil {
		return nil
	}
	out := &createspecv0.SpecRequest{}
	out.ContainerID = in.GetContainerId()
	out.Name = in.GetName()
	out.Spec = in.GetSpec()
	out.Labels = in.GetLabels()
	return out
}
