name: 'Setup Runner'
description: 'Composite action to set up the GitHub Runner for jobs in the test.yml workflow'

runs:
  using: composite
  steps:
    - run: |
        sudo modprobe ip_vs
        sudo modprobe ipv6
        sudo modprobe ip6table_filter
        sudo modprobe -r overlay
        sudo modprobe overlay redirect_dir=off
      shell: bash
    - run: |
        if [ ! -e /etc/docker/daemon.json ]; then
         echo '{}' | sudo tee /etc/docker/daemon.json >/dev/null
        fi
        DOCKERD_CONFIG=$(jq '.+{"experimental":true,"live-restore":true,"ipv6":true,"fixed-cidr-v6":"2001:db8:1::/64"}' /etc/docker/daemon.json)
        sudo tee /etc/docker/daemon.json <<<"$DOCKERD_CONFIG" >/dev/null
        sudo service docker restart
      shell: bash
    - run: |
        ./contrib/check-config.sh || true
      shell: bash
    - run: |
        docker info
      shell: bash
    # TODO: Remove this step once the separate action is merged
    # Github doesn't let you add a composite action and use it in the same PR (apparently)
    # Ref: https://github.com/moby/moby/actions/runs/5581571995/jobs/10199909170?pr=45652#step:9:1
    - run: |
        set -e
        docker run -d --net=host --name jaeger -e COLLECTOR_OTLP_ENABLED=true jaegertracing/all-in-one:1.46
        docker0_ip="$(ip -f inet addr show docker0 | grep -Po 'inet \K[\d.]+')"
        echo "OTEL_EXPORTER_OTLP_ENDPOINT=http://${docker0_ip}:4318" >> "${GITHUB_ENV}"
      shell: bash
