name: 'Setup Runner'
description: 'Composite action to set up the GitHub Runner for jobs in the test.yml workflow'

runs:
  using: composite
  steps:
    - run: |
        sudo modprobe ip_vs
        sudo modprobe ipv6
        sudo modprobe ip6table_filter
        sudo modprobe -r overlay
        sudo modprobe overlay redirect_dir=off
      shell: bash
    - run: |
        if [ ! -e /etc/docker/daemon.json ]; then
         echo '{}' | sudo tee /etc/docker/daemon.json >/dev/null
        fi
        DOCKERD_CONFIG=$(jq '.+{"experimental":true,"live-restore":true,"ipv6":true,"fixed-cidr-v6":"2001:db8:1::/64"}' /etc/docker/daemon.json)
        sudo tee /etc/docker/daemon.json <<<"$DOCKERD_CONFIG" >/dev/null
        sudo service docker restart
      shell: bash
    - run: |
        ./contrib/check-config.sh || true
      shell: bash
    - run: |
        docker info
      shell: bash
