# -*- mode: ruby -*-
# vi: set ft=ruby :

$BUILDBOT_IP = '192.168.33.21'

def v10(config)
  config.vm.box = "quantal64_3.5.0-25"
  config.vm.box_url = "http://get.docker.io/vbox/ubuntu/12.10/quantal64_3.5.0-25.box"
  config.vm.share_folder 'v-data', '/data/docker', File.dirname(__FILE__) + '/..'
  config.vm.network :hostonly, $BUILDBOT_IP

  # Ensure puppet is installed on the instance
  config.vm.provision :shell, :inline => 'apt-get -qq update; apt-get install -y puppet'

  config.vm.provision :puppet do |puppet|
    puppet.manifests_path = '.'
    puppet.manifest_file  = 'buildbot.pp'
    puppet.options = ['--templatedir','.']
  end
end

Vagrant::VERSION < '1.1.0' and Vagrant::Config.run do |config|
  v10(config)
end

Vagrant::VERSION >= '1.1.0' and Vagrant.configure('1') do |config|
  v10(config)
end
