// +build experimental

package namesgenerator

import (
	"fmt"

	"github.com/docker/docker/pkg/random"
)

var (
	left = [...]string{
		"acariatre",
		"accablant",
		"acerbe",
		"acide",
		"acre",
		"affreux",
		"agacant",
		"agaçant",
		"aigre",
		"amer",
		"antipathique",
		"apre",
		"assommant",
		"assoupissant",
		"assourdissant",
		"atrabilaire",
		"blessant",
		"bourru",
		"brusque",
		"casse-pieds",
		"cassecouille",
		"chagrinant",
		"chiant",
		"chiatique",
		"choquant",
		"contraignant",
		"contrariant",
		"criard",
		"crispant",
		"deplaisant",
		"desagreable",
		"desastreux",
		"desavantageux",
		"desobligeant",
		"detestable",
		"discordant",
		"disgracieux",
		"douloureux",
		"ecoeurant",
		"embetant",
		"emmerdant",
		"empoisonnant",
		"endormant",
		"enervant",
		"ennuyant",
		"ennuyeux",
		"enquiquinant",
		"etourdissant",
		"exasperant",
		"facheuse",
		"facheux",
		"fade",
		"fastidieux",
		"fatide",
		"fatigant",
		"fecheux",
		"ganant",
		"gonflant",
		"grimaçant",
		"grossier",
		"haissable",
		"harcelant",
		"hargneux",
		"horripilant",
		"hostile",
		"hypnagogique",
		"impoli",
		"impopulaire",
		"importun",
		"inamical",
		"incommodant",
		"incommode",
		"ingrat",
		"inhospitalier",
		"insipide",
		"insolent",
		"insupportable",
		"intolerable",
		"intraitable",
		"irritant",
		"laid",
		"lassant",
		"lourd",
		"lethargique",
		"malencontreux",
		"malheureux",
		"malplaisant",
		"maudit",
		"maussade",
		"mauvais",
		"mechant",
		"mesavenant",
		"moche",
		"mortel",
		"mourant",
		"narcotique",
		"nauseabond",
		"nauseeux",
		"obscene",
		"odieuse",
		"odieux",
		"offensant",
		"penible",
		"pesant",
		"puant",
		"putride",
		"rasant",
		"raseur",
		"rasoir",
		"rebutant",
		"refrigerant",
		"regrettable",
		"repoussant",
		"repugnant",
		"reveche",
		"rude",
		"sale",
		"saoulant",
		"saumatre",
		"sec",
		"sempiternel",
		"somnifere",
		"soporatif",
		"soporeux",
		"soporifique",
		"tourmentant",
		"vexant",
	}

	// Source: http://will.pagesperso-orange.fr/docu/dirigdt.htm
	right = [...]string{
		"auriol",
		"bidault",
		"blum",
		"bonaparte",
		"caribert",
		"carloman",
		"carnot",
		"casimir-perier",
		"charles",
		"childebert",
		"chilperic",
		"chirac",
		"clodomir",
		"clotaire",
		"clovis",
		"coty",
		"dagobert",
		"de-gaulle",
		"deschanel",
		"doumer",
		"doumergue",
		"eudes",
		"fallieres",
		"faure",
		"françois",
		"giscard",
		"gontran",
		"gouin",
		"grevy",
		"henri",
		"hugues-capet",
		"hollande",
		"jean",
		"lebrun",
		"lothaire",
		"loubet",
		"louis",
		"louis-philippe",
		"mac-mahon",
		"martel",
		"millerand",
		"mitterand",
		"napoleon",
		"pepin-le-bref",
		"petain",
		"philippe",
		"poincare",
		"pompidou",
		"raoul",
		"robert",
		"sarkozy",
		"sigebert",
		"theodebald",
		"thierry",
		"thiers",
		"clemenceau",
		"compte",
		"condorcet",
		"mendes",
		"robespierre",
		"rocard",
		"turgot",
	}
)

// GetRandomName generates a random name from the list of adjectives and surnames in this package
// formatted as "adjective_surname". For example 'focused_turing'. If retry is non-zero, a random
// integer between 0 and 10 will be added to the end of the name, e.g `focused_turing3`
func GetRandomName(retry int) string {
	rnd := random.Rand
	name := fmt.Sprintf("%s_%s", left[rnd.Intn(len(left))], right[rnd.Intn(len(right))])
	if retry > 0 {
		name = fmt.Sprintf("%s%d", name, rnd.Intn(10))
	}
	return name
}
