// Code generated by go-swagger; DO NOT EDIT.

package plugin

// Device device
//
// swagger:model Device
type Device struct {

	// description
	// Required: true
	Description string `json:"Description"`

	// name
	// Required: true
	Name string `json:"Name"`

	// path
	// Example: /dev/fuse
	// Required: true
	Path *string `json:"Path"`

	// settable
	// Required: true
	Settable []string `json:"Settable"`
}
