// Code generated by go-swagger; DO NOT EDIT.

package plugin

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

// Mount mount
//
// swagger:model Mount
type Mount struct {

	// description
	// Example: This is a mount that's used by the plugin.
	// Required: true
	Description string `json:"Description"`

	// destination
	// Example: /mnt/state
	// Required: true
	Destination string `json:"Destination"`

	// name
	// Example: some-mount
	// Required: true
	Name string `json:"Name"`

	// options
	// Example: ["rbind","rw"]
	// Required: true
	Options []string `json:"Options"`

	// settable
	// Required: true
	Settable []string `json:"Settable"`

	// source
	// Example: /var/lib/docker/plugins/
	// Required: true
	Source *string `json:"Source"`

	// type
	// Example: bind
	// Required: true
	Type string `json:"Type"`
}
