package errors // import "github.com/docker/docker/api/types/errors"

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

// Response Represents an error.
// swagger:model ErrorResponse
type Response struct {

	// The error message.
	// Required: true
	Message string `json:"message"`
}
