# ~/.bash_profile : executed by the command interpreter for login shells.

# if running bash
if [ -n "$BASH_VERSION" ]; then
    # include .bashrc if it exists
    if [ -f "$HOME/.bashrc" ]; then
        . "$HOME/.bashrc"
    fi
fi

# set PATH so it includes user's private bin if it exists
[ -d "$HOME/bin" ] && PATH="$HOME/bin:$PATH"

docker=/data/docker/src/github.com/dotcloud/docker
[ -d $docker ] && cd $docker

export GOPATH=/data/docker
export PATH=$PATH:$GOPATH/bin

