#!/usr/bin/env bash
#
# Run all validation

SCRIPTDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SCRIPTS=(
	default
	vendor
)

RET=0
for SCR in "${SCRIPTS[@]}"; do
	"${SCRIPTDIR}/$SCR" || RET=$?
done
exit $RET
