#!/usr/bin/env bash
#
# Run default validation, exclude vendor because it's slow

export SCRIPTDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

. ${SCRIPTDIR}/dco
. ${SCRIPTDIR}/default-seccomp
. ${SCRIPTDIR}/golangci-lint
. ${SCRIPTDIR}/pkg-imports
. ${SCRIPTDIR}/swagger
. ${SCRIPTDIR}/swagger-gen
. ${SCRIPTDIR}/toml
. ${SCRIPTDIR}/changelog-well-formed
. ${SCRIPTDIR}/changelog-date-descending
#. ${SCRIPTDIR}/deprecate-integration-cli
