#!/usr/bin/env bash
#
# Run default validation, exclude vendor because it's slow

SCRIPTDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Skip DCO check here, as it's already checked in a separate check in ci
#. "${SCRIPTDIR}"/dco
. "${SCRIPTDIR}"/pkg-imports
. "${SCRIPTDIR}"/deprecate-integration-cli
. "${SCRIPTDIR}"/golangci-lint
. "${SCRIPTDIR}"/shfmt
