#!/usr/bin/env bash
set -e -o pipefail

SCRIPTDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# CI platforms differ, so per-platform GOMETALINTER_OPTS can be set
# in the Jenkinsfile, otherwise let's just set a
# (somewhat pessimistic) default of 10 minutes.
: "${GOMETALINTER_OPTS=--deadline=10m}"

# shellcheck disable=SC2086
gometalinter \
	${GOMETALINTER_OPTS} \
	--config "${SCRIPTDIR}/gometalinter.json" ./...
