#!/usr/bin/env bash

SCRIPTDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPTDIR}/.validate"

IFS=$'\n'
files=($(validate_diff --diff-filter=ACMR --name-only -- 'api/types/' 'api/openapi.yaml' || true))
unset IFS

if [ -n "${TEST_FORCE_VALIDATE:-}" ] || [ ${#files[@]} -gt 0 ]; then
	"${SCRIPTDIR}"/../generate-openapi.sh 2> /dev/null
	# Let see if the working directory is clean
	diffs="$(git diff -- api/types/)"
	if [ "$diffs" ]; then
		{
			echo 'The result of hack/generate-openapi.sh differs'
			echo
			echo "$diffs"
			echo
			echo 'Please update api/openapi.yaml with any API changes, then '
			echo 'run hack/generate-openapi.sh.'
		} >&2
		false
	else
		echo 'Congratulations!  All API changes are done the right way.'
	fi
else
	echo 'No api/types/ or api/openapi.yaml changes in diff.'
fi
