#!/usr/bin/env bash
set -e -o pipefail

shfmtflags=(-bn -ci -sr -d "$@") # Allows to specify additional flags.
if shfmt -f . | grep -E -v '^vendor/' \
	| xargs shfmt "${shfmtflags[@]}"; then
	echo 'Congratulations! The shell scripts are properly formatted.'
else
	echo "Please reformat the shell scripts with \`$0 -w\`."
	exit 1
fi
