#!/usr/bin/env bash
set -e
# shellcheck disable=SC2155
export SCRIPTDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
# shellcheck disable=SC1090
source "${SCRIPTDIR}/.validate"

IFS=$'\n'
files=( $(validate_diff --diff-filter=ACMR --name-only -- 'api/swagger.yaml' || true) )
unset IFS

if [ ${#files[@]} -gt 0 ]; then
  yamllint -c ${SCRIPTDIR}/.swagger-yamllint api/swagger.yaml
  swagger validate api/swagger.yaml
fi
