#!/usr/bin/env bash

# shellcheck disable=SC2155
export SCRIPTDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
# shellcheck disable=SC1090
source "${SCRIPTDIR}/.validate"

IFS=$'\n'
files=( $(validate_diff --diff-filter=ACMR --name-only -- 'MAINTAINERS' || true) )
unset IFS

badFiles=()
for f in "${files[@]}"; do
	# we use "git show" here to validate that what's committed has valid toml syntax
	if ! git show "$VALIDATE_HEAD:$f" | tomlv /proc/self/fd/0 ; then
		badFiles+=( "$f" )
	fi
done

if [ ${#badFiles[@]} -eq 0 ]; then
	echo 'Congratulations!  All toml source files changed here have valid syntax.'
else
	{
		echo "These files are not valid toml:"
		for f in "${badFiles[@]}"; do
			echo " - $f"
		done
		echo
		echo 'Please reformat the above files as valid toml'
		echo
	} >&2
	false
fi
