#!/usr/bin/env bash
# Entrypoint for jenkins experimental CI
set -eu -o pipefail

# FixME: Just save some time during debug
exit 0

export DOCKER_EXPERIMENTAL=y

hack/make.sh \
	binary-daemon \
	test-integration
