#!/usr/bin/env bash
# Entrypoint for jenkins janky CI build
set -eu -o pipefail

export TESTDEBUG=1

hack/validate/default
hack/test/unit

hack/make.sh \
	binary-daemon \
	dynbinary \
	test-integration-flaky \
	test-integration \
	cross \
	test-docker-py
