#!/bin/sh
set -x
set -e

PACKAGE=github.com/dotcloud/docker

if [ $# -lt 3 ]; then
	echo "Usage: $0 REVISION AWS_ID AWS_KEY"
	exit 1
fi

export REVISION=$1 AWS_ID=$2 AWS_KEY=$3

START=$(pwd)
git clone "https://$PACKAGE" docker-checkout-$REVISION
cd docker-checkout-$REVISION
git checkout $REVISION

make
BUILDDIR=${START}/docker-$REVISION
cp -R ./bin $BUILDDIR

BUILD_ARCHIVE=${START}/docker-$REVISION.tgz
tar -f $BUILD_ARCHIVE -C $(dirname $BUILDDIR) -zc $(basename $BUILDDIR)
s3cmd -P put $BUILD_ARCHIVE s3://get.docker.io/builds/$(uname -s)/$(uname -m)/docker-$REVISION.tgz
