#!/bin/sh
set -x
set -e

PACKAGE=github.com/dotcloud/docker

if [ $# -lt 3 ]; then
	echo "Usage: $0 REVISION AWS_ID AWS_KEY"
	exit 1
fi

export REVISION=$1 AWS_ID=$2 AWS_KEY=$3

START=$(pwd)
mkdir -p go/src/$PACKAGE
git clone "https://$PACKAGE" go/src/$PACKAGE
cd go/src/$PACKAGE
git checkout $REVISION

# FIXME: checkout to specific revision

BUILDDIR=${START}/docker-$REVISION
mkdir -p $BUILDDIR
(export GOPATH=${START}/go; cd docker && go get -v && go build -v -o $BUILDDIR/docker)

BUILD_ARCHIVE=${START}/docker-$REVISION.tgz
tar -f $BUILD_ARCHIVE -C $(dirname $BUILDDIR) -zc $(basename $BUILDDIR)
s3cmd -P put $BUILD_ARCHIVE s3://get.docker.io/builds/$(uname -s)/$(uname -m)/docker-$REVISION.tgz
