pre {
    background-color: #F5F5F5;
    border: 1px solid rgba(0, 0, 0, 0.15);
    border-radius: 4px 4px 4px 4px;
    display: block;
    font-size: 13px;
    line-height: 20px;
    margin: 0 0 10px;
    padding: 9.5px;
    white-space: pre-wrap;
    word-break: break-all;
    word-wrap: break-word;
}
code, pre {
    border-radius: 3px 3px 3px 3px;
    color: #333333;
    font-family: Monaco,Menlo,Consolas,"Courier New",monospace;
    font-size: 12px;
    padding: 0 3px 2px;
}

.terminal {
	color: #AAAAAA;
	background-color: black;
}

.terminal  span.command {
	color: white;
	font-weight: bold;
}

.error_input {
    border-color: #B94A48 !important;
    box-shadow: 0 1px 1px rgba(0, 0, 0, 0.075) inset !important;
}

input.level {
    width: 150px;
    height: 2.5em;
    display: inline-block;
}
div.level_error {
    width: 300px;
    display: inline-block;
    padding: 7px 12px;
}
.alert {
    text-align:center;
}
#check_level_questions {
    margin-top: 10px;
}
.form-inline input.l_fill {
    height: 20px;
    border-radius: 0;
    width: 90px;
    margin-right: 0;
    padding: 0 0 2px 0;
}
.dockerfile.back {
    display: block;
    margin-top: 5px;
}