// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: github.com/docker/docker/container/stream/streamv2/stdio/stdio.proto

package stdio

import (
	context "context"
	fmt "fmt"
	github_com_containerd_ttrpc "github.com/containerd/ttrpc"
	proto "github.com/gogo/protobuf/proto"
	types "github.com/gogo/protobuf/types"
	io "io"
	math "math"
	math_bits "math/bits"
	reflect "reflect"
	strings "strings"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type StreamFraming_FramingType int32

const (
	// No framing
	StreamFraming_NONE StreamFraming_FramingType = 0
	// Use framing from github.com/docker/docker/pkg/stdcopy
	StreamFraming_STDCOPY StreamFraming_FramingType = 1
	// Websocket with text framing
	StreamFraming_WEBSOCKET_TEXT StreamFraming_FramingType = 2
	// Websocket with binary framing
	StreamFraming_WEBSOCKET_BINARY StreamFraming_FramingType = 3
)

var StreamFraming_FramingType_name = map[int32]string{
	0: "NONE",
	1: "STDCOPY",
	2: "WEBSOCKET_TEXT",
	3: "WEBSOCKET_BINARY",
}

var StreamFraming_FramingType_value = map[string]int32{
	"NONE":             0,
	"STDCOPY":          1,
	"WEBSOCKET_TEXT":   2,
	"WEBSOCKET_BINARY": 3,
}

func (x StreamFraming_FramingType) String() string {
	return proto.EnumName(StreamFraming_FramingType_name, int32(x))
}

func (StreamFraming_FramingType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_4c066d8b925c99ff, []int{2, 0}
}

// AttachStreamRequest is used to by the AttachStreams rpc to pass along references to file descriptors that the caller is requesting to attach with.
// Each file descriptor reference must be transferred to the stdio service before making this request.
// How the file descriptors are transferred to the stdio service is left up to the implementation to deal with.
//
// A nil descriptor means there is nothing to attach.
type AttachStreamsRequest struct {
	Stdin                *FileDescriptor `protobuf:"bytes,1,opt,name=stdin,proto3" json:"stdin,omitempty"`
	Stdout               *FileDescriptor `protobuf:"bytes,2,opt,name=stdout,proto3" json:"stdout,omitempty"`
	Stderr               *FileDescriptor `protobuf:"bytes,3,opt,name=stderr,proto3" json:"stderr,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *AttachStreamsRequest) Reset()      { *m = AttachStreamsRequest{} }
func (*AttachStreamsRequest) ProtoMessage() {}
func (*AttachStreamsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c066d8b925c99ff, []int{0}
}
func (m *AttachStreamsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *AttachStreamsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_AttachStreamsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *AttachStreamsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AttachStreamsRequest.Merge(m, src)
}
func (m *AttachStreamsRequest) XXX_Size() int {
	return m.Size()
}
func (m *AttachStreamsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AttachStreamsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AttachStreamsRequest proto.InternalMessageInfo

// AttachStreamRequest is used to by the AttachStreamsMultiplexed rpc to pass along references to file descriptors that the caller is requesting to attach with.
// Each file descriptor reference must be transferred to the stdio service before making this request.
// How the file descriptors are transferred to the stdio service is left up to the implementation to deal with.
type AttachStreamsMultiplexedRequest struct {
	// Stream specifies the file descriptor that will be used for sending/receiving stdio with framing.
	// Stream must never be nil.
	Stream  *FileDescriptor `protobuf:"bytes,1,opt,name=stream,proto3" json:"stream,omitempty"`
	Framing StreamFraming   `protobuf:"bytes,2,opt,name=framing,proto3" json:"framing"`
	// include_stdout and include_stderr denote which streams are to be multiplexed on the output stream.
	// At lease one must be specified or an error will be generated.
	IncludeStdin         bool     `protobuf:"varint,4,opt,name=include_stdin,json=includeStdin,proto3" json:"include_stdin,omitempty"`
	IncludeStdout        bool     `protobuf:"varint,5,opt,name=include_stdout,json=includeStdout,proto3" json:"include_stdout,omitempty"`
	IncludeStderr        bool     `protobuf:"varint,6,opt,name=include_stderr,json=includeStderr,proto3" json:"include_stderr,omitempty"`
	DetachKeys           []byte   `protobuf:"bytes,7,opt,name=detach_keys,json=detachKeys,proto3" json:"detach_keys,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AttachStreamsMultiplexedRequest) Reset()      { *m = AttachStreamsMultiplexedRequest{} }
func (*AttachStreamsMultiplexedRequest) ProtoMessage() {}
func (*AttachStreamsMultiplexedRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c066d8b925c99ff, []int{1}
}
func (m *AttachStreamsMultiplexedRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *AttachStreamsMultiplexedRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_AttachStreamsMultiplexedRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *AttachStreamsMultiplexedRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AttachStreamsMultiplexedRequest.Merge(m, src)
}
func (m *AttachStreamsMultiplexedRequest) XXX_Size() int {
	return m.Size()
}
func (m *AttachStreamsMultiplexedRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AttachStreamsMultiplexedRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AttachStreamsMultiplexedRequest proto.InternalMessageInfo

// StreamFraming defines how an stream should be framed
type StreamFraming struct {
	Type                 StreamFraming_FramingType `protobuf:"varint,1,opt,name=type,proto3,enum=docker.container.services.stdio.v1.StreamFraming_FramingType" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *StreamFraming) Reset()      { *m = StreamFraming{} }
func (*StreamFraming) ProtoMessage() {}
func (*StreamFraming) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c066d8b925c99ff, []int{2}
}
func (m *StreamFraming) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *StreamFraming) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_StreamFraming.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *StreamFraming) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StreamFraming.Merge(m, src)
}
func (m *StreamFraming) XXX_Size() int {
	return m.Size()
}
func (m *StreamFraming) XXX_DiscardUnknown() {
	xxx_messageInfo_StreamFraming.DiscardUnknown(m)
}

var xxx_messageInfo_StreamFraming proto.InternalMessageInfo

// FileDescriptor represents a reference to a file descriptor which should exist in the process of the stdio service.
//
// This will be used like so: `os.NewFile(desc.Fileno, desc.Name)`.
type FileDescriptor struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Fileno               uint32   `protobuf:"varint,2,opt,name=fileno,proto3" json:"fileno,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FileDescriptor) Reset()      { *m = FileDescriptor{} }
func (*FileDescriptor) ProtoMessage() {}
func (*FileDescriptor) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c066d8b925c99ff, []int{3}
}
func (m *FileDescriptor) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *FileDescriptor) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_FileDescriptor.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *FileDescriptor) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FileDescriptor.Merge(m, src)
}
func (m *FileDescriptor) XXX_Size() int {
	return m.Size()
}
func (m *FileDescriptor) XXX_DiscardUnknown() {
	xxx_messageInfo_FileDescriptor.DiscardUnknown(m)
}

var xxx_messageInfo_FileDescriptor proto.InternalMessageInfo

func init() {
	proto.RegisterEnum("docker.container.services.stdio.v1.StreamFraming_FramingType", StreamFraming_FramingType_name, StreamFraming_FramingType_value)
	proto.RegisterType((*AttachStreamsRequest)(nil), "docker.container.services.stdio.v1.AttachStreamsRequest")
	proto.RegisterType((*AttachStreamsMultiplexedRequest)(nil), "docker.container.services.stdio.v1.AttachStreamsMultiplexedRequest")
	proto.RegisterType((*StreamFraming)(nil), "docker.container.services.stdio.v1.StreamFraming")
	proto.RegisterType((*FileDescriptor)(nil), "docker.container.services.stdio.v1.FileDescriptor")
}

func init() {
	proto.RegisterFile("github.com/docker/docker/container/stream/streamv2/stdio/stdio.proto", fileDescriptor_4c066d8b925c99ff)
}

var fileDescriptor_4c066d8b925c99ff = []byte{
	// 577 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x54, 0xcb, 0x6e, 0xd3, 0x40,
	0x14, 0xcd, 0xa4, 0x79, 0x71, 0xd3, 0x44, 0xd1, 0x28, 0xaa, 0xa2, 0x20, 0x39, 0x91, 0x11, 0x52,
	0x56, 0xb6, 0x1a, 0x36, 0x15, 0x82, 0x45, 0xf3, 0xa8, 0x80, 0x8a, 0x84, 0x3a, 0x91, 0x68, 0xd9,
	0x44, 0x8e, 0x3d, 0x71, 0xac, 0x3a, 0x1e, 0x33, 0x1e, 0xa7, 0x64, 0xc7, 0x9f, 0xf0, 0x0f, 0x7c,
	0x45, 0x96, 0x2c, 0x58, 0xb0, 0x42, 0x34, 0x5f, 0xc1, 0x12, 0xd9, 0xe3, 0xd0, 0x06, 0x88, 0xe8,
	0x63, 0xe3, 0x19, 0x5f, 0x9f, 0x7b, 0xce, 0xcc, 0xb9, 0xf7, 0x1a, 0x3a, 0x96, 0xcd, 0xa7, 0xc1,
	0x58, 0x31, 0xe8, 0x4c, 0x35, 0xa9, 0x71, 0x4e, 0xd8, 0x7a, 0x31, 0xa8, 0xcb, 0x75, 0xdb, 0x25,
	0x4c, 0xf5, 0x39, 0x23, 0xfa, 0x2c, 0x5e, 0xe6, 0x4d, 0xd5, 0xe7, 0xa6, 0x4d, 0xc5, 0x53, 0xf1,
	0x18, 0xe5, 0x14, 0xcb, 0x22, 0x47, 0xf9, 0x9d, 0xa3, 0xf8, 0x84, 0xcd, 0x6d, 0x83, 0xf8, 0x8a,
	0x80, 0xcd, 0xf7, 0xab, 0x0f, 0x2d, 0x4a, 0x2d, 0x87, 0xa8, 0x51, 0xc6, 0x38, 0x98, 0xa8, 0x64,
	0xe6, 0xf1, 0x85, 0x20, 0xa8, 0x96, 0x2d, 0x6a, 0xd1, 0x68, 0xab, 0x86, 0x3b, 0x11, 0x95, 0x7f,
	0x22, 0x28, 0x1f, 0x72, 0xae, 0x1b, 0xd3, 0x41, 0xa4, 0xed, 0x6b, 0xe4, 0x7d, 0x40, 0x7c, 0x8e,
	0x5f, 0x40, 0x3a, 0xe4, 0x75, 0x2b, 0xa8, 0x8e, 0x1a, 0xf9, 0x66, 0x53, 0xf9, 0xbf, 0xbe, 0x72,
	0x64, 0x3b, 0xa4, 0x43, 0x7c, 0x83, 0xd9, 0x1e, 0xa7, 0x4c, 0x13, 0x04, 0xf8, 0x15, 0x64, 0x7c,
	0x6e, 0xd2, 0x80, 0x57, 0x92, 0x77, 0xa6, 0x8a, 0x19, 0x62, 0x2e, 0xc2, 0x58, 0x65, 0xe7, 0x5e,
	0x5c, 0x84, 0x31, 0xf9, 0x6b, 0x12, 0x6a, 0x1b, 0x57, 0x7f, 0x1d, 0x38, 0xdc, 0xf6, 0x1c, 0xf2,
	0x81, 0x98, 0x6b, 0x17, 0x22, 0xbd, 0xf0, 0xe3, 0x3d, 0x6c, 0x88, 0x19, 0xf0, 0x09, 0x64, 0x27,
	0x4c, 0x9f, 0xd9, 0xae, 0x15, 0x1b, 0xb1, 0x7f, 0x13, 0x32, 0x71, 0xb6, 0x23, 0x91, 0xd8, 0x4a,
	0x2d, 0xbf, 0xd7, 0x12, 0xda, 0x9a, 0x07, 0x3f, 0x82, 0x82, 0xed, 0x1a, 0x4e, 0x60, 0x92, 0x91,
	0x28, 0x56, 0xaa, 0x8e, 0x1a, 0x39, 0x6d, 0x37, 0x0e, 0x0e, 0x22, 0xff, 0x1f, 0x43, 0xf1, 0x1a,
	0x28, 0xac, 0x43, 0x3a, 0x42, 0x15, 0xae, 0x50, 0xa1, 0xb5, 0x9b, 0xb0, 0xd0, 0xe2, 0xcc, 0x9f,
	0x30, 0xc2, 0x18, 0xae, 0x41, 0xde, 0x24, 0xa1, 0x69, 0xa3, 0x73, 0xb2, 0xf0, 0x2b, 0xd9, 0x3a,
	0x6a, 0xec, 0x6a, 0x20, 0x42, 0xc7, 0x64, 0xe1, 0xcb, 0x9f, 0x11, 0x14, 0x36, 0x0e, 0x8d, 0x4f,
	0x20, 0xc5, 0x17, 0x1e, 0x89, 0x2c, 0x2c, 0x36, 0x9f, 0xdf, 0xfa, 0xd6, 0x4a, 0xbc, 0x0e, 0x17,
	0x1e, 0xd1, 0x22, 0x2a, 0xb9, 0x07, 0xf9, 0x6b, 0x41, 0x9c, 0x83, 0x54, 0xaf, 0xdf, 0xeb, 0x96,
	0x12, 0x38, 0x0f, 0xd9, 0xc1, 0xb0, 0xd3, 0xee, 0xbf, 0x39, 0x2b, 0x21, 0x8c, 0xa1, 0xf8, 0xb6,
	0xdb, 0x1a, 0xf4, 0xdb, 0xc7, 0xdd, 0xe1, 0x68, 0xd8, 0x3d, 0x1d, 0x96, 0x92, 0xb8, 0x0c, 0xa5,
	0xab, 0x58, 0xeb, 0x65, 0xef, 0x50, 0x3b, 0x2b, 0xed, 0xc8, 0xcf, 0xa0, 0xb8, 0x59, 0x35, 0x8c,
	0x21, 0xe5, 0xea, 0x33, 0x71, 0xe8, 0x07, 0x5a, 0xb4, 0xc7, 0x7b, 0x90, 0x99, 0xd8, 0x0e, 0x71,
	0x69, 0x54, 0xc0, 0x82, 0x16, 0xbf, 0x35, 0x3f, 0x25, 0x21, 0x1d, 0x7a, 0x4d, 0xb1, 0x0e, 0x85,
	0x8d, 0x96, 0xc2, 0x07, 0x37, 0xb9, 0xed, 0xbf, 0x06, 0xb0, 0xba, 0xa7, 0x88, 0x69, 0x56, 0xd6,
	0xd3, 0xac, 0x74, 0xc3, 0x69, 0xc6, 0x17, 0x50, 0xd9, 0xd6, 0xb5, 0xb8, 0x7d, 0x6b, 0xb5, 0xbf,
	0x7b, 0x7e, 0xab, 0xf0, 0x53, 0xc8, 0x0d, 0xa6, 0x01, 0x37, 0xe9, 0x85, 0x8b, 0xb7, 0x60, 0xb6,
	0xe5, 0xb6, 0xb4, 0xe5, 0xa5, 0x94, 0xf8, 0x76, 0x29, 0x25, 0x3e, 0xae, 0x24, 0xb4, 0x5c, 0x49,
	0xe8, 0xcb, 0x4a, 0x42, 0x3f, 0x56, 0x12, 0x7a, 0x77, 0x70, 0xd7, 0xbf, 0xe3, 0x29, 0x1a, 0x67,
	0x22, 0x95, 0x27, 0xbf, 0x02, 0x00, 0x00, 0xff, 0xff, 0x4c, 0xed, 0x7b, 0x0a, 0x62, 0x05, 0x00,
	0x00,
}

func (m *AttachStreamsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *AttachStreamsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *AttachStreamsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if m.Stderr != nil {
		{
			size, err := m.Stderr.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintStdio(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x1a
	}
	if m.Stdout != nil {
		{
			size, err := m.Stdout.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintStdio(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if m.Stdin != nil {
		{
			size, err := m.Stdin.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintStdio(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *AttachStreamsMultiplexedRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *AttachStreamsMultiplexedRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *AttachStreamsMultiplexedRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if len(m.DetachKeys) > 0 {
		i -= len(m.DetachKeys)
		copy(dAtA[i:], m.DetachKeys)
		i = encodeVarintStdio(dAtA, i, uint64(len(m.DetachKeys)))
		i--
		dAtA[i] = 0x3a
	}
	if m.IncludeStderr {
		i--
		if m.IncludeStderr {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x30
	}
	if m.IncludeStdout {
		i--
		if m.IncludeStdout {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x28
	}
	if m.IncludeStdin {
		i--
		if m.IncludeStdin {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x20
	}
	{
		size, err := m.Framing.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintStdio(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	if m.Stream != nil {
		{
			size, err := m.Stream.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintStdio(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *StreamFraming) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *StreamFraming) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *StreamFraming) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if m.Type != 0 {
		i = encodeVarintStdio(dAtA, i, uint64(m.Type))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *FileDescriptor) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *FileDescriptor) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *FileDescriptor) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if m.Fileno != 0 {
		i = encodeVarintStdio(dAtA, i, uint64(m.Fileno))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Name) > 0 {
		i -= len(m.Name)
		copy(dAtA[i:], m.Name)
		i = encodeVarintStdio(dAtA, i, uint64(len(m.Name)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintStdio(dAtA []byte, offset int, v uint64) int {
	offset -= sovStdio(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *AttachStreamsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Stdin != nil {
		l = m.Stdin.Size()
		n += 1 + l + sovStdio(uint64(l))
	}
	if m.Stdout != nil {
		l = m.Stdout.Size()
		n += 1 + l + sovStdio(uint64(l))
	}
	if m.Stderr != nil {
		l = m.Stderr.Size()
		n += 1 + l + sovStdio(uint64(l))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *AttachStreamsMultiplexedRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Stream != nil {
		l = m.Stream.Size()
		n += 1 + l + sovStdio(uint64(l))
	}
	l = m.Framing.Size()
	n += 1 + l + sovStdio(uint64(l))
	if m.IncludeStdin {
		n += 2
	}
	if m.IncludeStdout {
		n += 2
	}
	if m.IncludeStderr {
		n += 2
	}
	l = len(m.DetachKeys)
	if l > 0 {
		n += 1 + l + sovStdio(uint64(l))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *StreamFraming) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Type != 0 {
		n += 1 + sovStdio(uint64(m.Type))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *FileDescriptor) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Name)
	if l > 0 {
		n += 1 + l + sovStdio(uint64(l))
	}
	if m.Fileno != 0 {
		n += 1 + sovStdio(uint64(m.Fileno))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func sovStdio(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozStdio(x uint64) (n int) {
	return sovStdio(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (this *AttachStreamsRequest) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&AttachStreamsRequest{`,
		`Stdin:` + strings.Replace(this.Stdin.String(), "FileDescriptor", "FileDescriptor", 1) + `,`,
		`Stdout:` + strings.Replace(this.Stdout.String(), "FileDescriptor", "FileDescriptor", 1) + `,`,
		`Stderr:` + strings.Replace(this.Stderr.String(), "FileDescriptor", "FileDescriptor", 1) + `,`,
		`XXX_unrecognized:` + fmt.Sprintf("%v", this.XXX_unrecognized) + `,`,
		`}`,
	}, "")
	return s
}
func (this *AttachStreamsMultiplexedRequest) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&AttachStreamsMultiplexedRequest{`,
		`Stream:` + strings.Replace(this.Stream.String(), "FileDescriptor", "FileDescriptor", 1) + `,`,
		`Framing:` + strings.Replace(strings.Replace(this.Framing.String(), "StreamFraming", "StreamFraming", 1), `&`, ``, 1) + `,`,
		`IncludeStdin:` + fmt.Sprintf("%v", this.IncludeStdin) + `,`,
		`IncludeStdout:` + fmt.Sprintf("%v", this.IncludeStdout) + `,`,
		`IncludeStderr:` + fmt.Sprintf("%v", this.IncludeStderr) + `,`,
		`DetachKeys:` + fmt.Sprintf("%v", this.DetachKeys) + `,`,
		`XXX_unrecognized:` + fmt.Sprintf("%v", this.XXX_unrecognized) + `,`,
		`}`,
	}, "")
	return s
}
func (this *StreamFraming) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&StreamFraming{`,
		`Type:` + fmt.Sprintf("%v", this.Type) + `,`,
		`XXX_unrecognized:` + fmt.Sprintf("%v", this.XXX_unrecognized) + `,`,
		`}`,
	}, "")
	return s
}
func (this *FileDescriptor) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&FileDescriptor{`,
		`Name:` + fmt.Sprintf("%v", this.Name) + `,`,
		`Fileno:` + fmt.Sprintf("%v", this.Fileno) + `,`,
		`XXX_unrecognized:` + fmt.Sprintf("%v", this.XXX_unrecognized) + `,`,
		`}`,
	}, "")
	return s
}
func valueToStringStdio(v interface{}) string {
	rv := reflect.ValueOf(v)
	if rv.IsNil() {
		return "nil"
	}
	pv := reflect.Indirect(rv).Interface()
	return fmt.Sprintf("*%v", pv)
}

type StdioService interface {
	AttachStreams(ctx context.Context, req *AttachStreamsRequest) (*types.Empty, error)
	AttachStreamsMultiplexed(ctx context.Context, req *AttachStreamsMultiplexedRequest) (*types.Empty, error)
	Shutdown(ctx context.Context, req *types.Empty) (*types.Empty, error)
}

func RegisterStdioService(srv *github_com_containerd_ttrpc.Server, svc StdioService) {
	srv.Register("docker.container.services.stdio.v1.Stdio", map[string]github_com_containerd_ttrpc.Method{
		"AttachStreams": func(ctx context.Context, unmarshal func(interface{}) error) (interface{}, error) {
			var req AttachStreamsRequest
			if err := unmarshal(&req); err != nil {
				return nil, err
			}
			return svc.AttachStreams(ctx, &req)
		},
		"AttachStreamsMultiplexed": func(ctx context.Context, unmarshal func(interface{}) error) (interface{}, error) {
			var req AttachStreamsMultiplexedRequest
			if err := unmarshal(&req); err != nil {
				return nil, err
			}
			return svc.AttachStreamsMultiplexed(ctx, &req)
		},
		"Shutdown": func(ctx context.Context, unmarshal func(interface{}) error) (interface{}, error) {
			var req types.Empty
			if err := unmarshal(&req); err != nil {
				return nil, err
			}
			return svc.Shutdown(ctx, &req)
		},
	})
}

type stdioClient struct {
	client *github_com_containerd_ttrpc.Client
}

func NewStdioClient(client *github_com_containerd_ttrpc.Client) StdioService {
	return &stdioClient{
		client: client,
	}
}

func (c *stdioClient) AttachStreams(ctx context.Context, req *AttachStreamsRequest) (*types.Empty, error) {
	var resp types.Empty
	if err := c.client.Call(ctx, "docker.container.services.stdio.v1.Stdio", "AttachStreams", req, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

func (c *stdioClient) AttachStreamsMultiplexed(ctx context.Context, req *AttachStreamsMultiplexedRequest) (*types.Empty, error) {
	var resp types.Empty
	if err := c.client.Call(ctx, "docker.container.services.stdio.v1.Stdio", "AttachStreamsMultiplexed", req, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

func (c *stdioClient) Shutdown(ctx context.Context, req *types.Empty) (*types.Empty, error) {
	var resp types.Empty
	if err := c.client.Call(ctx, "docker.container.services.stdio.v1.Stdio", "Shutdown", req, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}
func (m *AttachStreamsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowStdio
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: AttachStreamsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: AttachStreamsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Stdin", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStdio
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthStdio
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthStdio
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Stdin == nil {
				m.Stdin = &FileDescriptor{}
			}
			if err := m.Stdin.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Stdout", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStdio
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthStdio
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthStdio
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Stdout == nil {
				m.Stdout = &FileDescriptor{}
			}
			if err := m.Stdout.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Stderr", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStdio
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthStdio
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthStdio
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Stderr == nil {
				m.Stderr = &FileDescriptor{}
			}
			if err := m.Stderr.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipStdio(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthStdio
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthStdio
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *AttachStreamsMultiplexedRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowStdio
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: AttachStreamsMultiplexedRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: AttachStreamsMultiplexedRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Stream", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStdio
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthStdio
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthStdio
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Stream == nil {
				m.Stream = &FileDescriptor{}
			}
			if err := m.Stream.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Framing", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStdio
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthStdio
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthStdio
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Framing.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field IncludeStdin", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStdio
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.IncludeStdin = bool(v != 0)
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field IncludeStdout", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStdio
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.IncludeStdout = bool(v != 0)
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field IncludeStderr", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStdio
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.IncludeStderr = bool(v != 0)
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DetachKeys", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStdio
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthStdio
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthStdio
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DetachKeys = append(m.DetachKeys[:0], dAtA[iNdEx:postIndex]...)
			if m.DetachKeys == nil {
				m.DetachKeys = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipStdio(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthStdio
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthStdio
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *StreamFraming) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowStdio
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: StreamFraming: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: StreamFraming: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Type", wireType)
			}
			m.Type = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStdio
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Type |= StreamFraming_FramingType(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipStdio(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthStdio
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthStdio
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *FileDescriptor) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowStdio
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: FileDescriptor: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: FileDescriptor: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Name", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStdio
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthStdio
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthStdio
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Name = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Fileno", wireType)
			}
			m.Fileno = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStdio
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Fileno |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipStdio(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthStdio
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthStdio
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipStdio(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowStdio
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowStdio
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowStdio
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthStdio
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupStdio
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthStdio
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthStdio        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowStdio          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupStdio = fmt.Errorf("proto: unexpected end of group")
)
