// Code generated by go-swagger; DO NOT EDIT.

package network

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

// SubnetStatus subnet status
//
// swagger:model SubnetStatus
type SubnetStatus struct {

	// Number of IP addresses in the subnet that are unavailable for allocation.
	//
	IPsInUse uint64 `json:"IPsInUse"`

	// Number of IP addresses that are available for dynamic allocation.
	//
	DynamicIPsAvailable uint64 `json:"DynamicIPsAvailable"`
}
