#!/usr/bin/env bash

SCRIPTDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPTDIR}/.validate"

IFS=$'\n'
files=($(validate_diff --diff-filter=ACMR --name-only -- 'types/' 'swagger.yaml' || true))
unset IFS

if [ -n "${TEST_FORCE_VALIDATE:-}" ] || [ ${#files[@]} -gt 0 ]; then
	"${SCRIPTDIR}"/generate-swagger-api.sh 2> /dev/null
	# Let see if the working directory is clean
	diffs="$(git diff -- types/)"
	if [ "$diffs" ]; then
		{
			echo 'The result of scripts/generate-swagger-api.sh differs'
			echo
			echo "$diffs"
			echo
			echo 'Please update swagger.yaml with any API changes, then '
			echo 'run scripts/generate-swagger-api.sh.'
		} >&2
		false
	else
		echo 'Congratulations!  All API changes are done the right way.'
	fi
else
	echo 'No types/ or swagger.yaml changes in diff.'
fi
