#!/usr/bin/env bash
set -Eeuo pipefail

if [[ $# -ne 2 ]]; then
	echo "usage: $0 <RELEASE_BRANCH> <TAG>" >&2
	exit 1
fi

release_branch="$1"
tag="$2"

# Return early the requested tag is already merged into release branch.
if git merge-base --is-ancestor "$tag" "$release_branch"; then
	exit 0
fi

# Get all docker release tags merged into master but not into release branch
git tag --merged upstream/master --no-merged "$release_branch" \
	| grep '^docker-v' \
	| grep -v -- "-rc." \
	| sort \
	| sed "/$tag/q"
