FROM 		debian
MAINTAINER	SvenDowideit@docker.com
#
#    docker build -t docsconvert . && docker run -v $(pwd):/docs docsconvert
#

RUN 	apt-get update && apt-get install -yq make python-pip python-setuptools
RUN	pip install mkdocs

RUN	apt-get install -yq vim-tiny git pandoc make

# pip installs from docs/requirements.txt, but here to increase cacheability
RUN pip install Sphinx==1.2.1
RUN pip install sphinxcontrib-httpdomain==1.2.0

CMD	bash
