// Code generated by go-swagger; DO NOT EDIT.

package volume

// ListResponse VolumeListResponse
//
// # Volume list response
//
// swagger:model ListResponse
type ListResponse struct {

	// List of volumes
	Volumes []Volume `json:"Volumes"`

	// Warnings that occurred when fetching the list of volumes.
	//
	// Example: []
	Warnings []string `json:"Warnings"`
}
