package volume

// ----------------------------------------------------------------------------
// DO NOT EDIT THIS FILE
// This file was generated by `swagger generate operation`
//
// See hack/generate-swagger-api.sh
// ----------------------------------------------------------------------------

// VolumesUpdateBody volume update body
// swagger:model VolumesUpdateBody
type VolumesUpdateBody struct {

	// A mapping of driver options and values to change. These options are passed directly to the driver and are driver specific.
	// Required: true
	DriverOpts map[string]string `json:"DriverOpts"`

	// A mapping of user-defined key/value metadata to update.
	// Required: true
	Labels map[string]string `json:"Labels"`
}
