// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: extpoints/storage/kv/v0/storage.proto

package protogen

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         []byte                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResponse) Reset() {
	*x = GetResponse{}
	mi := &file_extpoints_storage_kv_v0_storage_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResponse) ProtoMessage() {}

func (x *GetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_extpoints_storage_kv_v0_storage_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResponse.ProtoReflect.Descriptor instead.
func (*GetResponse) Descriptor() ([]byte, []int) {
	return file_extpoints_storage_kv_v0_storage_proto_rawDescGZIP(), []int{0}
}

func (x *GetResponse) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type ListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespace     string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Prefix        string                 `protobuf:"bytes,2,opt,name=prefix,proto3" json:"prefix,omitempty"`
	Limit         uint32                 `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	Cursor        string                 `protobuf:"bytes,4,opt,name=cursor,proto3" json:"cursor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRequest) Reset() {
	*x = ListRequest{}
	mi := &file_extpoints_storage_kv_v0_storage_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRequest) ProtoMessage() {}

func (x *ListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_extpoints_storage_kv_v0_storage_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRequest.ProtoReflect.Descriptor instead.
func (*ListRequest) Descriptor() ([]byte, []int) {
	return file_extpoints_storage_kv_v0_storage_proto_rawDescGZIP(), []int{1}
}

func (x *ListRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *ListRequest) GetPrefix() string {
	if x != nil {
		return x.Prefix
	}
	return ""
}

func (x *ListRequest) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListRequest) GetCursor() string {
	if x != nil {
		return x.Cursor
	}
	return ""
}

type ListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Keys          []string               `protobuf:"bytes,1,rep,name=keys,proto3" json:"keys,omitempty"`
	NextCursor    string                 `protobuf:"bytes,2,opt,name=next_cursor,json=nextCursor,proto3" json:"next_cursor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListResponse) Reset() {
	*x = ListResponse{}
	mi := &file_extpoints_storage_kv_v0_storage_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListResponse) ProtoMessage() {}

func (x *ListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_extpoints_storage_kv_v0_storage_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListResponse.ProtoReflect.Descriptor instead.
func (*ListResponse) Descriptor() ([]byte, []int) {
	return file_extpoints_storage_kv_v0_storage_proto_rawDescGZIP(), []int{2}
}

func (x *ListResponse) GetKeys() []string {
	if x != nil {
		return x.Keys
	}
	return nil
}

func (x *ListResponse) GetNextCursor() string {
	if x != nil {
		return x.NextCursor
	}
	return ""
}

type RecordRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespace     string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Key           string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecordRequest) Reset() {
	*x = RecordRequest{}
	mi := &file_extpoints_storage_kv_v0_storage_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordRequest) ProtoMessage() {}

func (x *RecordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_extpoints_storage_kv_v0_storage_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordRequest.ProtoReflect.Descriptor instead.
func (*RecordRequest) Descriptor() ([]byte, []int) {
	return file_extpoints_storage_kv_v0_storage_proto_rawDescGZIP(), []int{3}
}

func (x *RecordRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *RecordRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type WriteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespace     string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Key           string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Value         []byte                 `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteRequest) Reset() {
	*x = WriteRequest{}
	mi := &file_extpoints_storage_kv_v0_storage_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteRequest) ProtoMessage() {}

func (x *WriteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_extpoints_storage_kv_v0_storage_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteRequest.ProtoReflect.Descriptor instead.
func (*WriteRequest) Descriptor() ([]byte, []int) {
	return file_extpoints_storage_kv_v0_storage_proto_rawDescGZIP(), []int{4}
}

func (x *WriteRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *WriteRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *WriteRequest) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type CreateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateResponse) Reset() {
	*x = CreateResponse{}
	mi := &file_extpoints_storage_kv_v0_storage_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateResponse) ProtoMessage() {}

func (x *CreateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_extpoints_storage_kv_v0_storage_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateResponse.ProtoReflect.Descriptor instead.
func (*CreateResponse) Descriptor() ([]byte, []int) {
	return file_extpoints_storage_kv_v0_storage_proto_rawDescGZIP(), []int{5}
}

type UpdateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateResponse) Reset() {
	*x = UpdateResponse{}
	mi := &file_extpoints_storage_kv_v0_storage_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateResponse) ProtoMessage() {}

func (x *UpdateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_extpoints_storage_kv_v0_storage_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateResponse.ProtoReflect.Descriptor instead.
func (*UpdateResponse) Descriptor() ([]byte, []int) {
	return file_extpoints_storage_kv_v0_storage_proto_rawDescGZIP(), []int{6}
}

type DeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteResponse) Reset() {
	*x = DeleteResponse{}
	mi := &file_extpoints_storage_kv_v0_storage_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResponse) ProtoMessage() {}

func (x *DeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_extpoints_storage_kv_v0_storage_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResponse.ProtoReflect.Descriptor instead.
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return file_extpoints_storage_kv_v0_storage_proto_rawDescGZIP(), []int{7}
}

var File_extpoints_storage_kv_v0_storage_proto protoreflect.FileDescriptor

const file_extpoints_storage_kv_v0_storage_proto_rawDesc = "" +
	"\n" +
	"%extpoints/storage/kv/v0/storage.proto\x12'org.mobyproject.extension.storage.kv.v0\"#\n" +
	"\vGetResponse\x12\x14\n" +
	"\x05value\x18\x01 \x01(\fR\x05value\"q\n" +
	"\vListRequest\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12\x16\n" +
	"\x06prefix\x18\x02 \x01(\tR\x06prefix\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\rR\x05limit\x12\x16\n" +
	"\x06cursor\x18\x04 \x01(\tR\x06cursor\"C\n" +
	"\fListResponse\x12\x12\n" +
	"\x04keys\x18\x01 \x03(\tR\x04keys\x12\x1f\n" +
	"\vnext_cursor\x18\x02 \x01(\tR\n" +
	"nextCursor\"?\n" +
	"\rRecordRequest\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\"T\n" +
	"\fWriteRequest\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x03 \x01(\fR\x05value\"\x10\n" +
	"\x0eCreateResponse\"\x10\n" +
	"\x0eUpdateResponse\"\x10\n" +
	"\x0eDeleteResponse2\xe2\x04\n" +
	"\aStorage\x12s\n" +
	"\x03Get\x126.org.mobyproject.extension.storage.kv.v0.RecordRequest\x1a4.org.mobyproject.extension.storage.kv.v0.GetResponse\x12x\n" +
	"\x06Create\x125.org.mobyproject.extension.storage.kv.v0.WriteRequest\x1a7.org.mobyproject.extension.storage.kv.v0.CreateResponse\x12x\n" +
	"\x06Update\x125.org.mobyproject.extension.storage.kv.v0.WriteRequest\x1a7.org.mobyproject.extension.storage.kv.v0.UpdateResponse\x12y\n" +
	"\x06Delete\x126.org.mobyproject.extension.storage.kv.v0.RecordRequest\x1a7.org.mobyproject.extension.storage.kv.v0.DeleteResponse\x12s\n" +
	"\x04List\x124.org.mobyproject.extension.storage.kv.v0.ListRequest\x1a5.org.mobyproject.extension.storage.kv.v0.ListResponseB:Z8github.com/moby/moby/v2/extpoints/storage/kv/v0/protogenb\x06proto3"

var (
	file_extpoints_storage_kv_v0_storage_proto_rawDescOnce sync.Once
	file_extpoints_storage_kv_v0_storage_proto_rawDescData []byte
)

func file_extpoints_storage_kv_v0_storage_proto_rawDescGZIP() []byte {
	file_extpoints_storage_kv_v0_storage_proto_rawDescOnce.Do(func() {
		file_extpoints_storage_kv_v0_storage_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_extpoints_storage_kv_v0_storage_proto_rawDesc), len(file_extpoints_storage_kv_v0_storage_proto_rawDesc)))
	})
	return file_extpoints_storage_kv_v0_storage_proto_rawDescData
}

var file_extpoints_storage_kv_v0_storage_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_extpoints_storage_kv_v0_storage_proto_goTypes = []any{
	(*GetResponse)(nil),    // 0: org.mobyproject.extension.storage.kv.v0.GetResponse
	(*ListRequest)(nil),    // 1: org.mobyproject.extension.storage.kv.v0.ListRequest
	(*ListResponse)(nil),   // 2: org.mobyproject.extension.storage.kv.v0.ListResponse
	(*RecordRequest)(nil),  // 3: org.mobyproject.extension.storage.kv.v0.RecordRequest
	(*WriteRequest)(nil),   // 4: org.mobyproject.extension.storage.kv.v0.WriteRequest
	(*CreateResponse)(nil), // 5: org.mobyproject.extension.storage.kv.v0.CreateResponse
	(*UpdateResponse)(nil), // 6: org.mobyproject.extension.storage.kv.v0.UpdateResponse
	(*DeleteResponse)(nil), // 7: org.mobyproject.extension.storage.kv.v0.DeleteResponse
}
var file_extpoints_storage_kv_v0_storage_proto_depIdxs = []int32{
	3, // 0: org.mobyproject.extension.storage.kv.v0.Storage.Get:input_type -> org.mobyproject.extension.storage.kv.v0.RecordRequest
	4, // 1: org.mobyproject.extension.storage.kv.v0.Storage.Create:input_type -> org.mobyproject.extension.storage.kv.v0.WriteRequest
	4, // 2: org.mobyproject.extension.storage.kv.v0.Storage.Update:input_type -> org.mobyproject.extension.storage.kv.v0.WriteRequest
	3, // 3: org.mobyproject.extension.storage.kv.v0.Storage.Delete:input_type -> org.mobyproject.extension.storage.kv.v0.RecordRequest
	1, // 4: org.mobyproject.extension.storage.kv.v0.Storage.List:input_type -> org.mobyproject.extension.storage.kv.v0.ListRequest
	0, // 5: org.mobyproject.extension.storage.kv.v0.Storage.Get:output_type -> org.mobyproject.extension.storage.kv.v0.GetResponse
	5, // 6: org.mobyproject.extension.storage.kv.v0.Storage.Create:output_type -> org.mobyproject.extension.storage.kv.v0.CreateResponse
	6, // 7: org.mobyproject.extension.storage.kv.v0.Storage.Update:output_type -> org.mobyproject.extension.storage.kv.v0.UpdateResponse
	7, // 8: org.mobyproject.extension.storage.kv.v0.Storage.Delete:output_type -> org.mobyproject.extension.storage.kv.v0.DeleteResponse
	2, // 9: org.mobyproject.extension.storage.kv.v0.Storage.List:output_type -> org.mobyproject.extension.storage.kv.v0.ListResponse
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_extpoints_storage_kv_v0_storage_proto_init() }
func file_extpoints_storage_kv_v0_storage_proto_init() {
	if File_extpoints_storage_kv_v0_storage_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeFor[x]().PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_extpoints_storage_kv_v0_storage_proto_rawDesc), len(file_extpoints_storage_kv_v0_storage_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_extpoints_storage_kv_v0_storage_proto_goTypes,
		DependencyIndexes: file_extpoints_storage_kv_v0_storage_proto_depIdxs,
		MessageInfos:      file_extpoints_storage_kv_v0_storage_proto_msgTypes,
	}.Build()
	File_extpoints_storage_kv_v0_storage_proto = out.File
	file_extpoints_storage_kv_v0_storage_proto_goTypes = nil
	file_extpoints_storage_kv_v0_storage_proto_depIdxs = nil
}
