// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: extpoints/containernamegenerator/v0/container_name_generator.proto

package protogen

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GenerateContainerNameReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateContainerNameReply) Reset() {
	*x = GenerateContainerNameReply{}
	mi := &file_extpoints_containernamegenerator_v0_container_name_generator_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateContainerNameReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateContainerNameReply) ProtoMessage() {}

func (x *GenerateContainerNameReply) ProtoReflect() protoreflect.Message {
	mi := &file_extpoints_containernamegenerator_v0_container_name_generator_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateContainerNameReply.ProtoReflect.Descriptor instead.
func (*GenerateContainerNameReply) Descriptor() ([]byte, []int) {
	return file_extpoints_containernamegenerator_v0_container_name_generator_proto_rawDescGZIP(), []int{0}
}

func (x *GenerateContainerNameReply) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GenerateContainerNameRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Retry         int64                  `protobuf:"varint,1,opt,name=retry,proto3" json:"retry,omitempty"`
	ContainerId   string                 `protobuf:"bytes,2,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
	Image         string                 `protobuf:"bytes,3,opt,name=image,proto3" json:"image,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateContainerNameRequest) Reset() {
	*x = GenerateContainerNameRequest{}
	mi := &file_extpoints_containernamegenerator_v0_container_name_generator_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateContainerNameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateContainerNameRequest) ProtoMessage() {}

func (x *GenerateContainerNameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_extpoints_containernamegenerator_v0_container_name_generator_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateContainerNameRequest.ProtoReflect.Descriptor instead.
func (*GenerateContainerNameRequest) Descriptor() ([]byte, []int) {
	return file_extpoints_containernamegenerator_v0_container_name_generator_proto_rawDescGZIP(), []int{1}
}

func (x *GenerateContainerNameRequest) GetRetry() int64 {
	if x != nil {
		return x.Retry
	}
	return 0
}

func (x *GenerateContainerNameRequest) GetContainerId() string {
	if x != nil {
		return x.ContainerId
	}
	return ""
}

func (x *GenerateContainerNameRequest) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

var File_extpoints_containernamegenerator_v0_container_name_generator_proto protoreflect.FileDescriptor

const file_extpoints_containernamegenerator_v0_container_name_generator_proto_rawDesc = "" +
	"\n" +
	"Bextpoints/containernamegenerator/v0/container_name_generator.proto\x123org.mobyproject.extension.containernamegenerator.v0\"0\n" +
	"\x1aGenerateContainerNameReply\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"m\n" +
	"\x1cGenerateContainerNameRequest\x12\x14\n" +
	"\x05retry\x18\x01 \x01(\x03R\x05retry\x12!\n" +
	"\fcontainer_id\x18\x02 \x01(\tR\vcontainerId\x12\x14\n" +
	"\x05image\x18\x03 \x01(\tR\x05image2\xd6\x01\n" +
	"\x16ContainerNameGenerator\x12\xbb\x01\n" +
	"\x15GenerateContainerName\x12Q.org.mobyproject.extension.containernamegenerator.v0.GenerateContainerNameRequest\x1aO.org.mobyproject.extension.containernamegenerator.v0.GenerateContainerNameReplyBFZDgithub.com/moby/moby/v2/extpoints/containernamegenerator/v0/protogenb\x06proto3"

var (
	file_extpoints_containernamegenerator_v0_container_name_generator_proto_rawDescOnce sync.Once
	file_extpoints_containernamegenerator_v0_container_name_generator_proto_rawDescData []byte
)

func file_extpoints_containernamegenerator_v0_container_name_generator_proto_rawDescGZIP() []byte {
	file_extpoints_containernamegenerator_v0_container_name_generator_proto_rawDescOnce.Do(func() {
		file_extpoints_containernamegenerator_v0_container_name_generator_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_extpoints_containernamegenerator_v0_container_name_generator_proto_rawDesc), len(file_extpoints_containernamegenerator_v0_container_name_generator_proto_rawDesc)))
	})
	return file_extpoints_containernamegenerator_v0_container_name_generator_proto_rawDescData
}

var file_extpoints_containernamegenerator_v0_container_name_generator_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_extpoints_containernamegenerator_v0_container_name_generator_proto_goTypes = []any{
	(*GenerateContainerNameReply)(nil),   // 0: org.mobyproject.extension.containernamegenerator.v0.GenerateContainerNameReply
	(*GenerateContainerNameRequest)(nil), // 1: org.mobyproject.extension.containernamegenerator.v0.GenerateContainerNameRequest
}
var file_extpoints_containernamegenerator_v0_container_name_generator_proto_depIdxs = []int32{
	1, // 0: org.mobyproject.extension.containernamegenerator.v0.ContainerNameGenerator.GenerateContainerName:input_type -> org.mobyproject.extension.containernamegenerator.v0.GenerateContainerNameRequest
	0, // 1: org.mobyproject.extension.containernamegenerator.v0.ContainerNameGenerator.GenerateContainerName:output_type -> org.mobyproject.extension.containernamegenerator.v0.GenerateContainerNameReply
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_extpoints_containernamegenerator_v0_container_name_generator_proto_init() }
func file_extpoints_containernamegenerator_v0_container_name_generator_proto_init() {
	if File_extpoints_containernamegenerator_v0_container_name_generator_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeFor[x]().PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_extpoints_containernamegenerator_v0_container_name_generator_proto_rawDesc), len(file_extpoints_containernamegenerator_v0_container_name_generator_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_extpoints_containernamegenerator_v0_container_name_generator_proto_goTypes,
		DependencyIndexes: file_extpoints_containernamegenerator_v0_container_name_generator_proto_depIdxs,
		MessageInfos:      file_extpoints_containernamegenerator_v0_container_name_generator_proto_msgTypes,
	}.Build()
	File_extpoints_containernamegenerator_v0_container_name_generator_proto = out.File
	file_extpoints_containernamegenerator_v0_container_name_generator_proto_goTypes = nil
	file_extpoints_containernamegenerator_v0_container_name_generator_proto_depIdxs = nil
}
