#!/bin/sh

DEST=$1

if ! go run vendor/src/github.com/wagerlabs/nex/nex.go -e -o buildfile_lexer.go buildfile.nex; then
    echo "Could not invoke nex, run vendor.sh once to pull in this dependency"
    exit 1
fi

if ! go tool yacc -o buildfile_parser.go buildfile.y; then 
    echo "Failed to generate buildfile_parser.go from buildfile.y"
    exit 1
fi

if go build -o $DEST/docker-$VERSION -ldflags "$LDFLAGS" ./docker; then
	echo "Created binary: $DEST/docker-$VERSION"
fi
