#!/usr/bin/env bash
set -e

[ -z "$KEEPDEST" ] && rm -rf "$DEST"

(
	if [ -n "$DEST" ] && [ -z "$OUTPUT" ]; then
		OUTPUT="$(dirname "$DEST")/binary"
		export OUTPUT
	fi
	export CGO_ENABLED=0
	export PACKAGE=./cmd/docker-proxy
	. hack/make/.binary
)
