#!/usr/bin/env bash
set -e

[ -z "$KEEPDEST" ] && \
	rm -rf "$DEST"

# shellcheck disable=1090
(
	source "${MAKEDIR}/.binary-setup"
	export BINARY_SHORT_NAME="$DOCKER_CLIENT_BINARY_NAME"
	export GO_PACKAGE='github.com/docker/docker/cmd/docker'
	source "${MAKEDIR}/.binary"
)
