#!/bin/bash
set -e

[ -z "$KEEPDEST" ] && \
	rm -rf "$DEST"

(
	source "${MAKEDIR}/.binary-setup"
	export BINARY_SHORT_NAME="$DOCKER_DAEMON_BINARY_NAME"
	export SOURCE_PATH='./cmd/dockerd'
	source "${MAKEDIR}/.binary"
	export BINARY_SHORT_NAME="$DOCKER_PROXY_BINARY_NAME"
	export SOURCE_PATH='./vendor/src/github.com/docker/libnetwork/cmd/proxy'
	source "${MAKEDIR}/.binary"
	copy_binaries "$DEST" 'hash'
)
