#!/bin/bash

DEST=$1

go build \
	-o "$DEST/docker-$VERSION" \
	"${BUILDFLAGS[@]}" \
	-ldflags "
		$LDFLAGS
		$LDFLAGS_STATIC_DOCKER
	" \
	./docker
echo "Created binary: $DEST/docker-$VERSION"

hash_files "$DEST/docker-$VERSION"
