#!/usr/bin/env bash
set -e

[ -z "$KEEPDEST" ] && \
	rm -rf "$DEST"

(
	source "${MAKEDIR}/.binary-setup"
	export BINARY_SHORT_NAME="$DOCKER_DAEMON_BINARY_NAME"
	export GO_PACKAGE='github.com/docker/docker/cmd/dockerd'
	source "${MAKEDIR}/.binary"
	copy_binaries "$DEST" 'hash'
)
