#!/bin/bash
set -e

rm -rf "$DEST"
DEST="$DEST/../test-integration-cli"

if [ -z $DOCKER_INTEGRATION_TESTS_VERIFIED ]; then
	source ${MAKEDIR}/.integration-test-helpers
	ensure_test_dir integration-cli "$DEST/test.main"
	export DOCKER_INTEGRATION_TESTS_VERIFIED=1
fi
