#!/usr/bin/env bash
set -e

rm -rf "$DEST"
DEST="$ABS_DEST/../test-integration"

if [ -z $DOCKER_INTEGRATION_TESTS_VERIFIED ]; then
	source ${MAKEDIR}/.integration-test-helpers
	ensure_test_dir integration "$DEST/test.main"
	export DOCKER_INTEGRATION_TESTS_VERIFIED=1
fi
