#!/usr/bin/env bash
set -e

CONTAINER_UTILITY_COMMIT=e004a1415a433447369e315b9d7df357102be0d2 # v0.9.0

(
	git clone https://github.com/docker/windows-container-utility.git "$GOPATH/src/github.com/docker/windows-container-utility"
	cd "$GOPATH/src/github.com/docker/windows-container-utility"
	git checkout -q "$CONTAINER_UTILITY_COMMIT"

	echo Building: ${DEST}/containerutility.exe

	(
		make
	)

	mkdir -p ${ABS_DEST}

	cp containerutility.exe ${ABS_DEST}/containerutility.exe
)
