#!/bin/bash
set -e

platform="darwin/amd64"
export DEST="$DEST/$platform" # bundles/VERSION/darwin/darwin/amd64/docker-VERSION
mkdir -p "$DEST"
ABS_DEST="$(cd "$DEST" && pwd -P)"
export GOOS=${platform%/*}
export GOARCH=${platform##*/}
export LDFLAGS_STATIC_DOCKER="" # we just need a simple client
export BUILDFLAGS=( "${ORIG_BUILDFLAGS[@]/ daemon/}" ) # remove the "daemon" build tag
source "${MAKEDIR}/binary-client"
