#!/usr/bin/env bash
set -e

(
	export BINARY_SHORT_NAME='docker'
	export GO_PACKAGE='github.com/docker/docker/cmd/docker'
	export IAMSTATIC='false'
	export LDFLAGS_STATIC_DOCKER=''
	export BUILDFLAGS=( "${BUILDFLAGS[@]/netgo /}" ) # disable netgo, since we don't need it for a dynamic binary
	export BUILDFLAGS=( "${BUILDFLAGS[@]/static_build /}" ) # we're not building a "static" binary here
	source "${MAKEDIR}/.binary"
)
