#!/usr/bin/env bash
set -e

# This script exists as backwards compatibility for CI
# shellcheck disable=1091,2030
(
    DEST="${DEST}-client"
    ABS_DEST="${ABS_DEST}-client"
    . hack/make/dynbinary-client
)
# shellcheck disable=1091,2031
(
    DEST="${DEST}-daemon"
    ABS_DEST="${ABS_DEST}-daemon"
    . hack/make/dynbinary-daemon
)
