#!/usr/bin/env bash

set -e
rm -rf "$DEST"

install_binary() {
	local file="$1"
	local target="${DOCKER_MAKE_INSTALL_PREFIX:=/usr/local}/bin/"
	if [ "$(go env GOOS)" == "linux" ]; then
		echo "Installing $(basename $file) to ${target}"
		mkdir -p "$target"
		cp -f -L "$file" "$target"
	else
		echo "Install is only supported on linux"
		return 1
	fi
}

(
	DEST="$(dirname $DEST)/binary-daemon"
	source "${MAKEDIR}/.binary-setup"
	install_binary "${DEST}/${DAEMON_BINARY_NAME}"
	install_binary "${DEST}/${RUNC_BINARY_NAME}"
	install_binary "${DEST}/${CONTAINERD_BINARY_NAME}"
	install_binary "${DEST}/${CONTAINERD_CTR_BINARY_NAME}"
	install_binary "${DEST}/${CONTAINERD_SHIM_BINARY_NAME}"
	install_binary "${DEST}/${PROXY_BINARY_NAME}"
	install_binary "${DEST}/${INIT_BINARY_NAME}"
)
