#!/usr/bin/env bash

set -e
rm -rf "$DEST"

install_binary() {
	local file="$1"
	local target="${DOCKER_MAKE_INSTALL_PREFIX:=/usr/local}/bin/"
	if [ "$(go env GOOS)" == "linux" ]; then
		echo "Installing $(basename $file) to ${target}"
		mkdir -p "$target"
		cp -f -L "$file" "$target"
	else
		echo "Install is only supported on linux"
		return 1
	fi
}

(
	DEST="$(dirname $DEST)/binary-daemon"
	install_binary "${DEST}/dockerd"
	install_binary "${DEST}/runc"
	install_binary "${DEST}/containerd"
	install_binary "${DEST}/ctr"
	install_binary "${DEST}/containerd-shim"
	install_binary "${DEST}/containerd-shim-runc-v2"
	install_binary "${DEST}/docker-proxy"
	install_binary "${DEST}/docker-init"
	install_binary "${DEST}/rootlesskit"
	install_binary "${DEST}/rootlesskit-docker-proxy"
	install_binary "${DEST}/dockerd-rootless.sh"
	install_binary "${DEST}/dockerd-rootless-setuptool.sh"
	if [ -f "${DEST}/vpnkit" ]; then
		install_binary "${DEST}/vpnkit"
	fi
)
