#!/usr/bin/env bash

set -e
rm -rf "$DEST"

# shellcheck disable=SC1090
(
	DEST="$(dirname "$DEST")/binary-client"
	source "${MAKEDIR}/.binary-setup"
	install_binary "${DEST}/${DOCKER_CLIENT_BINARY_NAME}"
)
