#!/bin/bash
set -e

DEST=$1

# subshell so that we can export PATH without breaking other things
(
	source "$(dirname "$BASH_SOURCE")/.integration-daemon-start"

	# we need to wrap up everything in between integration-daemon-start and
	# integration-daemon-stop to make sure we kill the daemon and don't hang,
	# even and especially on test failures
	didFail=
	if ! {
		dockerPy='/docker-py'
		[ -d "$dockerPy" ] || {
			dockerPy="$DEST/docker-py"
			git clone https://github.com/docker/docker-py.git "$dockerPy"
		}

		# exporting PYTHONPATH to import "docker" from our local docker-py
		test_env PYTHONPATH="$dockerPy" python "$dockerPy/tests/integration_test.py"
	}; then
		didFail=1
	fi

	source "$(dirname "$BASH_SOURCE")/.integration-daemon-stop"

	[ -z "$didFail" ] # "set -e" ftw
) 2>&1 | tee -a $DEST/test.log
