#!/bin/bash
set -e

bundle_test_integration_cli() {
	TESTFLAGS="$TESTFLAGS -check.v -check.timeout=${TIMEOUT} -test.timeout=360m"
	(
		cd integration-cli
		export DEST="$ABS_DEST" # we're in a subshell, so this is safe -- our integration-cli tests need DEST, and "cd" screws it up
		go_test_pkgs .
	)
}

# subshell so that we can export PATH without breaking other things
(
	bundle .integration-daemon-start

	bundle .integration-daemon-setup

	bundle_test_integration_cli

	bundle .integration-daemon-stop

	if [ "$(go env GOOS)" != 'windows' ]
	then
		leftovers=$(ps -ax -o pid,cmd | awk '$2 == "docker-containerd-shim" && $4 ~ /.*\/bundles\/.*\/test-integration-cli/ { print $1 }')
		if [ -n "$leftovers" ]
		then
			ps aux
			kill -9 $leftovers 2> /dev/null
			echo "!!!! WARNING you have left over shim(s), Cleanup your test !!!!"
			exit 1
		fi
	fi

) 2>&1 | tee -a "$DEST/test.log"
