#!/bin/bash
set -e

DEST=$1

bundle_test_integration() {
	LDFLAGS="$LDFLAGS $LDFLAGS_STATIC_DOCKER" go_test_dir ./integration \
		"-coverpkg $(find_dirs '*.go' | sed 's,^\.,github.com/dotcloud/docker,g' | paste -d, -s)"
}

# this "grep" hides some really irritating warnings that "go test -coverpkg"
# spews when it is given packages that aren't used
bundle_test_integration 2>&1 \
	| grep --line-buffered -v '^warning: no packages being tested depend on ' \
	| tee $DEST/test.log
