#!/bin/bash

DEST="$1"
CROSS="$DEST/../cross"

set -e

if [ ! -d "$CROSS/linux/amd64" ]; then
	echo >&2 'error: binary and cross must be run before tgz'
	false
fi

for d in "$CROSS/"*/*; do
	GOARCH="$(basename "$d")"
	GOOS="$(basename "$(dirname "$d")")"
	mkdir -p "$DEST/$GOOS/$GOARCH"
	TGZ="$DEST/$GOOS/$GOARCH/docker-$VERSION.tgz"
	
	mkdir -p "$DEST/build"
	
	mkdir -p "$DEST/build/usr/local/bin"
	cp -L "$d/docker-$VERSION" "$DEST/build/usr/local/bin/docker"
	
	tar --numeric-owner --owner 0 -C "$DEST/build" -czf "$TGZ" usr
	
	hash_files "$TGZ"
	
	rm -rf "$DEST/build"
	
	echo "Created tgz: $TGZ"
done
