#!/usr/bin/env bash
set -e

[ -z "$KEEPDEST" ] && \
	rm -rf "$DEST"

# shellcheck disable=SC1090
(
	source "${MAKEDIR}/.binary-setup"
	export BINARY_SHORT_NAME="yaml-docs-generator"
	export GO_PACKAGE='github.com/docker/docker/docs/yaml'
	source "${MAKEDIR}/.binary"
)
