// Code generated by go-swagger; DO NOT EDIT.

package storage

// Storage Information about the storage used by the container.
//
// swagger:model Storage
type Storage struct {

	// Information about the storage used for the container's root filesystem.
	//
	RootFS *RootFSStorage `json:"RootFS,omitempty"`
}
