name: windows-2025

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

on:
  workflow_dispatch:
  push:
    branches:
      - 'master'
      - '[0-9]+.[0-9]+'
      - '[0-9]+.x'
  pull_request:

jobs:
  validate-dco:
    uses: ./.github/workflows/.dco.yml

  run:
    needs: validate-dco
    if: ${{ github.event_name != 'pull_request' || !contains(github.event.pull_request.labels.*.name, 'ci/validate-only') }}
    uses: ./.github/workflows/.windows.yml
    strategy:
      fail-fast: false
      matrix:
        storage:
          - graphdriver
          - snapshotter
    with:
      os: windows-2025
      storage: ${{ matrix.storage }}
      send_coverage: false
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
