# commit to be tagged for new release
commit = "HEAD"

project_name = "moby"
github_repo = "moby/moby"
sub_path = "api"
ignore_deps = [ "github.com/moby/moby" ]

# previous release
previous = "v28.2.2"

pre_release = true

preface = """\
The first dedicated release for the Moby API. This release continues the 1.x
line of API compatibility with the 52nd minor release of the 1.x API.
"""
